### ISSUE TITLE
Eth2OutgoingRequestHandler | Encountered error while processing response: IllegalStateException

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2477] opened 2020-07-29 08:15 UTC
ERROR level incident in my logs. I am including the immediately prior WARN notification in case it is relevant.

```
2020-07-29 00:14:07.292+00:00 | p2p-async-3 | WARN  | PeerSync | Failed to import block from peer (err: UNKNOWN_PARENT) SignedBeaconBlock{message=BeaconBlock{root=0x4afd44a5ffa3c8bc93943b14a4d3bce78546857fe4a62a9d92fd5d42764aa1c1, slot=212250, proposer_index=5140, parent_root=0x0880fc6d2c11cad9ebb169a980eaebe2848623423baa2155d461fcc0fbedebd1, state_root=0x453a2a32686985feba79f26e1308db58987783440b5814d302d455c5bed5082a, body=0x8ef7f5322e1bb23be50f8cf4654eb5af8d371abd70127781a54c8e07bcf77fcf}, signature=0xac96077fcaf0a07fd30d3a0a65d58fc1e7620a14aa6e721516873691b38759d3cf63b5efae3f50f3e3e184914e9f3dea00b35774802eed3e4632cbf055c64224bcab97de48a1a103dae912fbc728aa5ae49018c22cbe2f6b719e41e892dde083}: Eth2Peer{id=16Uiu2HAmTX6vDcoATZ5X5ikAxgfTsU7U5Xan8DcC1FaNG6YqUdTr, remoteStatus=Optional[PeerStatus{forkDigest=0xfdca39b0, finalizedRoot=0x70904936fb326cd88d29dc9eeb85fe4a1cc78d3e6c29c2649ab07bb526097a2b, finalizedEpoch=6633, headRoot=0x8c1eac31591edbb8369891b4b907a421b2d815c138bb8f75c1aa5bd3342fa5db, headSlot=212320}]}
2020-07-29 00:14:07.297+00:00 | nioEventLoopGroup-3-8 | ERROR | Eth2OutgoingRequestHandler | Encountered error while processing response
java.lang.IllegalStateException: New response submitted after closing AsyncResponseProcessor for new responses: SignedBeaconBlock{message=BeaconBlock{root=0x39f607240695e21e15863294edd6e8f98f745783b4b05d0e5ca29a700eda0f6a, slot=212261, proposer_index=65, parent_root=0xd9cd020f73ada62e1e840bc57e1ed5edce7885bfb86404daf0177e8fea986349, state_root=0x196e65b89ca1a79267a736b2778e8bfdc32dc058b9dcd6d476bb7c2419a1e430, body=0x0d51d5d221fb48ea6bdb9b20fb96f0a936a3caabecd0bb33ec6a7c3856a8445e}, signature=0x94230da78889f1133452f15aab0b7ce298cc45ff121e82a52f4d6cc55b920a9a6ead5971e597b7048c9a90467dc2effe1786623c6539d33e656d3d69def0e9d9f20c74bdfd865a86669d482cdd6b27e2702fffa57baf947be8eca1517f1b8bac}
        at tech.pegasys.teku.networking.eth2.rpc.core.AsyncResponseProcessor.processResponse(AsyncResponseProcessor.java:53) ~[teku-networking-eth2-0.12.2-SNAPSHOT.jar:0.12.2-dev-fb9e13c7]
        at java.util.ArrayList.forEach(ArrayList.java:1507) ~[?:?]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.processData(Eth2OutgoingRequestHandler.java:96) [teku-networking-eth2-0.12.2-SNAPSHOT.jar:0.12.2-dev-fb9e13c7]
        at tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.channelRead0(RpcHandler.java:143) [teku-networking-p2p-0.12.2-SNAPSHOT.jar:0.12.2-dev-fb9e13c7]
        at tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.channelRead0(RpcHandler.java:118) [teku-networking-p2p-0.12.2-SNAPSHOT.jar:0.12.2-dev-fb9e13c7]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.libp2p.etc.util.netty.mux.AbstractMuxHandler.childRead(AbstractMuxHandler.kt:55) [jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.libp2p.mux.MuxHandler.channelRead(MuxHandler.kt:39) [jvm-libp2p-minimal-0.5.3-RELEASE.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:830) [?:?]
```

Teku version: teku/v0.12.2-dev-fb9e13c7/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13

**Comment by mbaxter** [comment] 2020-07-29 16:15
Looks like the source of the problem is here: https://github.com/PegaSysEng/teku/blob/01ebad0c3d1a74dc939aeb6dbdeea1cb196589aa/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/Eth2OutgoingRequestHandler.java#L96

This throws a noisy error in the following scenario:
* We decode multiple responses at once [here](https://github.com/PegaSysEng/teku/blob/01ebad0c3d1a74dc939aeb6dbdeea1cb196589aa/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/Eth2OutgoingRequestHandler.java#L96)
* One of the earlier responses is invalid, causing us to [cancel processing](https://github.com/PegaSysEng/teku/blob/01ebad0c3d1a74dc939aeb6dbdeea1cb196589aa/networking/eth2/src/main/java/tech/pegasys/teku/networking/eth2/rpc/core/Eth2OutgoingRequestHandler.java#L130-L132)
* But we are still iterating through and delivering responses leading to this illegal state

**Comment by rolfyone** [comment] 2020-11-17 05:16
these messages are still appearing on Medalla, about 18 times in the last 24 hours.

It almost looks like a sync issue around finalizing and switching forks some how but I really don't know enough around that area to dig much further...

I saw one on Merediths box, but also several on the aws nodes that are running master.

I haven't seen any with the exception thrown afterwards, just with the initial `Failed to import block from peer (err: UNKNOWN_PARENT)` message.

**Comment by Nashatyrev** [comment] 2020-11-17 07:05
I'll check this. 
@rolfyone can you please share your exception cause there could be small but significant differences with the original one in this issue

**Comment by rolfyone** [comment] 2020-11-17 20:53
the exception I haven't found a recurrence of, only the initial message. I think there's another ticket with just the 'unknown parent' message, maybe it'd be less confusing to close this ticket, and I'd move my notes above to that?

**Comment by Nashatyrev** [comment] 2020-11-18 09:46
@rolfyone right, I didn't find any way how to reproduce the `IllegalStateException` with the current code so I'm closing this. 
Please move the desired comments to the 'unknown parent' issue you mentioned

**Closed as completed by Nashatyrev** 2020-11-18 09:46 UTC
Labels: bug 🐞, P5
