### ISSUE TITLE
Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.services.beaconchain.BeaconChainController'

### ISSUE THREAD

**Issue by dankrad** [Consensys-Incorporated/teku#2594] opened 2020-08-17 21:24 UTC
Getting this once per second

2020-08-17 22:24:15.747+01:00 | TimeTickChannel-0 | ERROR | teku-status-log | PLEASE FIX OR REPORT | Unexpected exception thrown for event 'interface tech.pegasys.teku.util.time.channels.TimeTickChannel.onTick' in handler 'tech.pegasys.teku.services.beaconchain.BeaconChainController'
java.util.concurrent.CompletionException: java.lang.RuntimeException: ProtoNode: Delta to be subtracted is greater than node weight.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:757) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108) ~[?:?]
	at tech.pegasys.teku.infrastructure.async.SafeFuture.thenAccept(SafeFuture.java:351) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.processHead(ForkChoice.java:64) ~[teku-ethereum-statetransition-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.processHead(ForkChoice.java:56) ~[teku-ethereum-statetransition-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.services.beaconchain.SlotProcessor.processSlotWhileSyncing(SlotProcessor.java:129) ~[teku-services-beaconchain-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.services.beaconchain.SlotProcessor.onTick(SlotProcessor.java:100) ~[teku-services-beaconchain-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.services.beaconchain.BeaconChainController.onTick(BeaconChainController.java:555) ~[teku-services-beaconchain-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.events.DirectEventDeliverer.deliverTo(DirectEventDeliverer.java:54) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverTo$0(AsyncEventDeliverer.java:61) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) [teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) [teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.RuntimeException: ProtoNode: Delta to be subtracted is greater than node weight.
	at tech.pegasys.teku.protoarray.ProtoNode.adjustWeight(ProtoNode.java:66) ~[teku-protoarray-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.protoarray.ProtoArray.applyScoreChanges(ProtoArray.java:175) ~[teku-protoarray-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategy.findHead(ProtoArrayForkChoiceStrategy.java:217) ~[teku-protoarray-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.protoarray.ProtoArrayForkChoiceStrategy.findHead(ProtoArrayForkChoiceStrategy.java:81) ~[teku-protoarray-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$processHead$2(ForkChoice.java:69) ~[teku-ethereum-statetransition-0.12.4-SNAPSHOT.jar:0.12.4-dev-c6548285]
	at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) ~[?:?]
	... 19 more

**Comment by dankrad** [comment] 2020-08-17 21:25
[tekulog.zip](https://github.com/PegaSysEng/teku/files/5086872/tekulog.zip)

**Comment by rolfyone** [comment] 2020-08-17 21:35
Thanks for the bug report.

We've got a ticket running for this issue, so we'll close this as a duplicate of #2562

**Closed as completed by rolfyone** 2020-08-17 21:35 UTC
