### ISSUE TITLE
Failed to process blocks by range request

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2020] opened 2020-06-01 09:49 UTC
I am periodically seeing pages and pages of this in the log.

```
2020-06-01 08:32:52.134+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event *** Slot: 38564, Block:    ... empty, Epoch: 1205, Finalized checkpoint: 1170, Finalized root: 0x0a36..9588, Peers: 30^[[0m
2020-06-01 08:32:57.050+00:00 | LibP2PNetwork-634 | ERROR | BeaconBlocksByRangeMessageHandler | Failed to process blocks by range request
java.util.concurrent.CompletionException: tech.pegasys.teku.networking.p2p.rpc.RpcStream$StreamClosedException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1190) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.sendNextBlock(BeaconBlocksByRangeMessageHandler.java:97) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.lambda$sendNextBlock$3(BeaconBlocksByRangeMessageHandler.java:104) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.sendNextBlock(BeaconBlocksByRangeMessageHandler.java:97) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.lambda$sendNextBlock$3(BeaconBlocksByRangeMessageHandler.java:104) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.sendNextBlock(BeaconBlocksByRangeMessageHandler.java:97) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.lambda$sendNextBlock$3(BeaconBlocksByRangeMessageHandler.java:104) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.sendNextBlock(BeaconBlocksByRangeMessageHandler.java:97) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.lambda$sendNextBlock$3(BeaconBlocksByRangeMessageHandler.java:104) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.sendNextBlock(BeaconBlocksByRangeMessageHandler.java:97) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.lambda$sendNextBlock$3(BeaconBlocksByRangeMessageHandler.java:104) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.sendNextBlock(BeaconBlocksByRangeMessageHandler.java:97) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.lambda$sendNextBlock$3(BeaconBlocksByRangeMessageHandler.java:104) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312) ~[teku-util-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
        at tech.pegasys.teku.networking.eth2.rpc.beaconchain.methods.BeaconBlocksByRangeMessageHandler.sendNextBlock(BeaconBlocksByRangeMessageHandler.java:97) ~[teku-networking-eth2-0.11.3-SNAPSHOT.jar:0.11.3-dev-c7e4825a]
<snip a few thousand identical lines...>
```

**Comment by ajsutton** [comment] 2020-06-02 00:46
Thanks for logging these errors - we need to gradually work through them all and fix or silence.  This one's a duplicate of #2018

**Closed as completed by ajsutton** 2020-06-02 00:46 UTC
