### ISSUE TITLE
Failed to propose block due to aggregation bits and committee not having the same length

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2577] opened 2020-08-14 21:51 UTC
This looks different from #2576. Seen on Medalla testnet. Note the "ERROR - Validator   *** Failed to produce block" in the middle.

```
21:32:56.086 WARN  - process_attestations: Attestation aggregation bits and committee don't have the same length
21:32:56.086 WARN  - State Transition error
tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_attestations: Attestation aggregation bits and committee don't have the same length
        at tech.pegasys.teku.core.BlockProcessorUtil.process_attestations_no_validation(BlockProcessorUtil.java:364) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.BlockProcessorUtil.process_operations_no_validation(BlockProcessorUtil.java:202) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.lambda$process_block$2(StateTransition.java:136) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.datastructures.state.BeaconStateImpl.updated(BeaconStateImpl.java:247) ~[teku-ethereum-datastructures-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.process_block(StateTransition.java:131) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:103) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:75) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:78) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:109) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:155) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:169) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$thenApplyChecked$20(SafeFuture.java:327) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:364) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApplyChecked(SafeFuture.java:324) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createFromBlockAndState(ValidatorApiHandler.java:164) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createUnsignedBlock(ValidatorApiHandler.java:152) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) [teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) [teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.IllegalArgumentException: process_attestations: Attestation aggregation bits and committee don't have the same length
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-29.0-jre.jar:?]
        at tech.pegasys.teku.core.BlockProcessorUtil.process_attestations_no_validation(BlockProcessorUtil.java:345) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        ... 29 more
21:32:56.087 ERROR - Validator   *** Failed to produce block  Slot: 74564
tech.pegasys.teku.core.StateTransitionException: tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_attestations: Attestation aggregation bits and committee>
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:118) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:75) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.BlockProposalUtil.createNewUnsignedBlock(BlockProposalUtil.java:78) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.BlockFactory.createUnsignedBlock(BlockFactory.java:109) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createUnsignedBlock$3(ValidatorApiHandler.java:155) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.lambda$createFromBlockAndState$4(ValidatorApiHandler.java:169) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$thenApplyChecked$20(SafeFuture.java:327) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183) ~[?:?]
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2306) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.thenCompose(SafeFuture.java:364) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.thenApplyChecked(SafeFuture.java:324) ~[teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createFromBlockAndState(ValidatorApiHandler.java:164) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.validator.coordinator.ValidatorApiHandler.createUnsignedBlock(ValidatorApiHandler.java:152) ~[teku-validator-coordinator-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at tech.pegasys.teku.events.DirectEventDeliverer.executeMethod(DirectEventDeliverer.java:74) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.events.DirectEventDeliverer.deliverToWithResponse(DirectEventDeliverer.java:67) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.events.AsyncEventDeliverer.lambda$deliverToWithResponse$1(AsyncEventDeliverer.java:75) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.deliverNextEvent(AsyncEventDeliverer.java:117) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.events.AsyncEventDeliverer$QueueReader.run(AsyncEventDeliverer.java:109) ~[teku-events-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: java.lang.IllegalArgumentException: process_attestations: Attestation aggregation bits and committee don't have the same length
        at tech.pegasys.teku.core.BlockProcessorUtil.process_attestations_no_validation(BlockProcessorUtil.java:364) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.BlockProcessorUtil.process_operations_no_validation(BlockProcessorUtil.java:202) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.lambda$process_block$2(StateTransition.java:136) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.datastructures.state.BeaconStateImpl.updated(BeaconStateImpl.java:247) ~[teku-ethereum-datastructures-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.process_block(StateTransition.java:131) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:103) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        ... 24 more
Caused by: java.lang.IllegalArgumentException: process_attestations: Attestation aggregation bits and committee don't have the same length
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142) ~[guava-29.0-jre.jar:?]
        at tech.pegasys.teku.core.BlockProcessorUtil.process_attestations_no_validation(BlockProcessorUtil.java:345) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.BlockProcessorUtil.process_operations_no_validation(BlockProcessorUtil.java:202) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.lambda$process_block$2(StateTransition.java:136) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.datastructures.state.BeaconStateImpl.updated(BeaconStateImpl.java:247) ~[teku-ethereum-datastructures-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.process_block(StateTransition.java:131) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:103) ~[teku-ethereum-core-0.12.4-SNAPSHOT.jar:0.12.4-dev-df300e3b]
        ... 24 more
```
### Versions (Add all that apply)
* Software version: teku/v0.12.4-dev-df300e3b/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13
* Java version: openjdk 13.0.3 2020-04-14
* OS Name & Version: Ubuntu 20.04.1 LTS

**Comment by ajsutton** [comment] 2020-08-25 00:02
I suspect this is a duplicate of #2576. The committee sizes may differ on different forks - especially as they diverge for some time because the number of active validators can vary.

**Comment by ajsutton** [comment] 2020-08-25 10:27
In fact, going to close this one as a duplicate of #2576.

**Closed as completed by ajsutton** 2020-08-25 10:27 UTC
Labels: bug 🐞, P2
