### ISSUE TITLE
PLEASE FIX OR REPORT | Unexpected exception thrown for events-async-8

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#6654] opened 2022-12-31 18:16 UTC
Incident [reported on discord](https://discord.com/channels/697535391594446898/697539289042649190/1058599473959403611).

Logs are [here](https://logpaste.com/HEnuwD9P). The relevant part copied below. Looks like not a lot to go on. May be related to a previous error reported a minute earlier `ERROR - Failed to process event queue for client 921726489`.

Use reports that the incident was isolated and everything is running fine since.

```
consensus_1                  | 2022-12-31 04:00:49.151 ERROR - PLEASE FIX OR REPORT | Unexpected exception thrown for events-async-8
consensus_1                  | java.util.concurrent.CompletionException: java.lang.IllegalStateException: s=OPEN,api=BLOCKED,sc=false,e=null
consensus_1                  | at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:603) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$exceptionallyCompose$33(SafeFuture.java:422) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.postComplete(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source) ~[?:?]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:146) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.CompletableFuture.whenComplete(Unknown Source) ~[?:?]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:603) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:33) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:143) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:316) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
consensus_1                  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
consensus_1                  | at java.lang.Thread.run(Unknown Source) ~[?:?]
consensus_1                  | Caused by: java.lang.IllegalStateException: s=OPEN,api=BLOCKED,sc=false,e=null
consensus_1                  | at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:813) ~[jetty-server-11.0.12.jar:11.0.12]
consensus_1                  | at org.eclipse.jetty.server.HttpOutput.print(HttpOutput.java:1126) ~[jetty-server-11.0.12.jar:11.0.12]
consensus_1                  | at org.eclipse.jetty.server.HttpOutput.print(HttpOutput.java:1053) ~[jetty-server-11.0.12.jar:11.0.12]
consensus_1                  | at io.javalin.http.sse.Emitter.write(Emitter.kt:42) ~[javalin-5.2.0.jar:5.2.0]
consensus_1                  | at io.javalin.http.sse.Emitter.emit(Emitter.kt:34) ~[javalin-5.2.0.jar:5.2.0]
consensus_1                  | at io.javalin.http.sse.SseClient.sendComment(SseClient.kt:81) ~[javalin-5.2.0.jar:5.2.0]
consensus_1                  | at tech.pegasys.teku.beaconrestapi.handlers.v1.events.EventSubscriber.lambda$keepAlive$4(EventSubscriber.java:147) ~[teku-data-beaconrestapi-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:155) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAfterDelay$1(AsyncRunner.java:32) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:74) ~[teku-infrastructure-async-22.12.0.jar:22.12.0]
consensus_1                  | ... 4 more
```

**Comment by lucassaldanha** [comment] 2023-01-12 21:15
@benjaminion I believe this is the first time we have seen a report like this, and the user has reported that everything was normal afterwards.

I don't think we have enough to determine what has happened. I'd probably keep an eye out for similar reports but I am tempted to close this as not reproducible for now. Thoughts?

**Comment by lucassaldanha** [comment] 2023-01-12 22:23
@rolfyone raised a good point that this is happening as part of an SSE sendComment and isn't a critical thing. We might want to better handle this error when we call SseClient (potentially ignore it for sendComment errors).

**Comment by benjaminion** [comment] 2023-01-12 22:25
Might be worth eyeballing the code to where the IllegalStateException could have occurred, in case anything jumps out. But looks like the exact location might be hard to track down.

Just saw the latest comment - if it's not significant it would definitely be better to trap it.

Bottom line: not worth spending ages on, but worth a few mins investigating or supressing it if possible.

**Comment by lucassaldanha** [comment] 2023-01-12 22:32
> But looks like the exact location might be hard to track down.

I believe there are only two places that Teku would send an SSE comment so it isn't too bad :)

**Comment by lucassaldanha** [comment] 2023-01-17 01:21
This seems to be similar to an old Jetty issue https://github.com/eclipse/jetty.project/issues/4461 that has been fixed in 2020. However, it looks like some other people have reported seeing it after the fix went out.

In any case, it is happening when sending an sse comment for keep-alive so we can probably log a warning and swallow it.

**Closed as completed** 2023-01-17 09:10 UTC
Labels: bug 🐞
