### ISSUE TITLE
AbstractRouter internal error on message null from peer null

### ISSUE THREAD

**Issue by fab-10** [Consensys-Incorporated/teku#6088] opened 2022-08-17 16:22 UTC
### Description
Since the update to Teku 22.8.0 yesterday, I have seen a couple of these errors `AbstractRouter internal error on message null from peer null`, never seen before, stack trace:

```
 io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
	at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:106)
	at io.libp2p.etc.util.P2PService.streamDisconnected(P2PService.kt:169)
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:92)
	at io.libp2p.etc.util.P2PService$StreamHandler$channelUnregistered$1.invoke(P2PService.kt:90)
	at io.libp2p.etc.util.P2PService.runOnEventThread$lambda-0(P2PService.kt:234)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### Steps to Reproduce (Bug)
Run Teku 22.8.0, it is not deterministic, it happened twice in a day

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Frequency:** [How regularly does it occur?]
it happened twice in a day

### Versions (Add all that apply)
* Software version: 22.8.0
* Java version: Java17

**Comment by ajsutton** [comment] 2022-08-17 23:22
Thanks, we'll look into this. FYI @Nashatyrev though you don't necessarily have to look into it. :)

**Comment by Nashatyrev** [comment] 2022-08-18 13:58
Yep, the same on my side after the update

**Comment by jimmygchen** [comment] 2022-08-18 22:29
Running into the same issue as well, got a bit curious and was wondering if it has anything to do with this recent change in [jvm-libp2p](https://github.com/libp2p/jvm-libp2p):


`P2PService.kt`
![image](https://user-images.githubusercontent.com/742762/185505423-cc94afcc-fba1-4278-bc58-baa722b8dbd2.png)


I'm not familiar with the code but it looks like `stream.getPeerHandler` is called even when steam is closed on initialization, which would always throw due to `peerHandler` not being set, as documented here:
![image](https://user-images.githubusercontent.com/742762/185505896-b303666b-c5dd-4a7a-ab85-e185c36d2710.png)


I've raised a PR here, but not sure how to reproduce and test - may need some feedback from someone familiar with the code base:
https://github.com/libp2p/jvm-libp2p/pull/254

**Comment by Nashatyrev** [comment] 2022-08-19 16:40
The WARN has gone when running with merged https://github.com/libp2p/jvm-libp2p/pull/254, thanks @jimmygchen !
So the issue could be closed when the next libp2p version integrated

**Closed as completed** 2022-08-26 00:10 UTC
