### ISSUE TITLE
Implement a mev-boost circuit breaker

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#5988] opened 2022-07-28 14:53 UTC
### Description
One suggestion is https://hackmd.io/@ralexstokes/BJn9N6Thc but discussions are continuing about the best approach. Just logging this so we ensure we have something and don't forget it.

**Comment by tbenr** [comment] 2022-08-16 17:48
duplicate of #6058

**Closed as completed by tbenr** 2022-08-16 17:48 UTC
