### ISSUE TITLE
Error: Produced invalid attestation for slot N: Signature is invalid

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2179] opened 2020-06-21 18:02 UTC
Seen this on three separate occasions on the Witti network today:

```
2020-06-21 00:51:28.318+00:00 | ValidatorApiChannel-0 | INFO  | teku-validator-log | ^[[34mValidator   *** Published attestation  Count: 1, Slot: 180257, Root: e029d2..8b75^[[0m
2020-06-21 00:51:28.342+00:00 | ValidatorApiChannel-0 | ERROR | teku-validator-log | ^[[31mValidator   *** Produced invalid attestation for slot 180257: Signature is invalid^[[0m
2020-06-21 00:51:32.323+00:00 | ValidatorApiChannel-0 | INFO  | teku-validator-log | ^[[34mValidator   *** Published aggregate    Count: 1, Slot: 180257, Root: e029d2..8b75^[[0m
```

This looks a bit weird.

It's possibly related to a large number of warnings in my logs about attestations with invalid signatures:

```
2020-06-21 01:14:12.409+00:00 | SlotEventsChannel-3 | WARN  | StateTransition | State Transition error
tech.pegasys.teku.core.exceptions.BlockProcessingException: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
        at tech.pegasys.teku.core.StateTransition.initiate(StateTransition.java:87) ~[teku-ethereum-core-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
        at tech.pegasys.teku.core.ForkChoiceUtil.on_block(ForkChoiceUtil.java:224) ~[teku-ethereum-core-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
        at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.onBlock(ForkChoice.java:65) ~[teku-ethereum-statetransition-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
        at tech.pegasys.teku.statetransition.blockimport.BlockImporter.importBlock(BlockImporter.java:70) ~[teku-ethereum-statetransition-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
        at tech.pegasys.teku.sync.BlockManager.importBlock(BlockManager.java:122) ~[teku-sync-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
...
Caused by: tech.pegasys.teku.core.exceptions.BlockProcessingException: Invalid attestation: Signature is invalid
        at tech.pegasys.teku.core.BlockProcessorUtil.verify_attestations(BlockProcessorUtil.java:399) ~[teku-ethereum-core-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
        at tech.pegasys.teku.core.blockvalidator.SimpleBlockValidator.validatePreState(SimpleBlockValidator.java:78) ~[teku-ethereum-core-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
        at tech.pegasys.teku.core.blockvalidator.BatchBlockValidator.validatePreState(BatchBlockValidator.java:43) ~[teku-ethereum-core-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
        at tech.pegasys.teku.core.blockvalidator.BlockValidator.validate(BlockValidator.java:88) ~[teku-ethereum-core-0.11.5-SNAPSHOT.jar:0.11.5-dev-d95fc0d1]
...
```

I have dozens of these mesages throughout the day. I don't know how invalid attestations are getting into blocks. In any case, there seem to be many badly signed attestations floating around, and we need to make sure we don't try to build them into aggregates.

**Comment by Nashatyrev** [comment] 2020-06-23 17:55
#### Observation:
Validator produced attestation for the slot `68550`

```
20:47:21.105 INFO  - Slot Event  *** Slot: 68549, Block: c2039e..2c6e, Epoch: 2142, Finalized checkpoint: 2140, Finalized root: 64cacf..464c, Peers: 54
20:47:29.264 INFO  - Slot Event  *** Slot: 68550, Block:    ... empty, Epoch: 2142, Finalized checkpoint: 2140, Finalized root: 64cacf..464c, Peers: 54
produceAttestationsForCommittee: 68550, 4
Invalid attestation: Attestation{aggregation_bits=000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000, data=AttestationData{slot=68550, index=4, beacon_block_root=0xc2039e84736babf548cdcda96dda143c71c91d075cc259faee2d4caaa56a2c6e, source=Checkpoint{epoch=2141, root=0xec7ab50c51657e2122cb0505ed0449d79cd3850c20e5f08647760cbfdd358af3}, target=Checkpoint{epoch=2142, root=0x46fa9b5dff989007afaf64ef289f8558d8fe9dc7606ae0449291e6675abb3e15}}, signature=0x84f5d612fbbe92b2fe22096dbfe50f97fd5d5fa099b4085e8899a2bce4bab889efa01ca7cfb85fea334de13e4184c17106eab14d5949ca13f3a54b10d8fc3bbedb634ef63e946ad412170d369da27a3db0410b27e62670e2d29bb22559314e4c}
20:47:29.467 ERROR - Validator   *** Produced invalid attestation for slot 68550: Signature is invalid
```

While API returns the `68549` slot for validator attestation: 
```json
{
  "epoch": "2142",
  "pubkeys": [
    "b6e880d58ec0d07a1490e65d3e38820d8dff3f093da8dacbb585cf884c403051def1544b7cda27870b90be4c8e53fea0"
  ]
}
```
```json
[
  {
    "validator_pubkey": "0xb6e880d58ec0d07a1490e65d3e38820d8dff3f093da8dacbb585cf884c403051def1544b7cda27870b90be4c8e53fea0",
    "aggregator_modulo": 8,
    "validator_index": 1974,
    "attestation_committee_index": 2,
    "attestation_committee_position": 59,
    "block_proposal_slots": [],
    "attestation_slot": "68549"
  }
]
```

**Comment by benjaminion** [comment] 2020-06-30 14:46
[Report](https://discord.com/channels/595666850260713488/724994681460490260/727527681293549638) of this "in the wild" on the Altona testnet.

**Comment by Phistr90** [comment] 2020-06-30 16:09
As @benjaminion pointed out I experienced this bug on the altona testnet. Find attached the log file of my node.
[teku.log](https://github.com/PegaSysEng/teku/files/4853081/teku.log)

**Comment by cemozerr** [comment] 2020-06-30 17:36
One interesting thing to note is that all of these signatures are invalid because the expected validator index for all these attestations is all sorts of different validator indices, yet the actual attestation validator index is always either 1266 or 1267.

**Comment by Nashatyrev** [comment] 2020-07-01 11:59
> 
> 
> One interesting thing to note is that all of these signatures are invalid because the expected validator index for all these attestations is all sorts of different validator indices, yet the actual attestation validator index is always either 1266 or 1267.

@cemozerr if we are producing an attestation for wrong slot (as I mentioned above) then the attester index would be calculated incorrectly. Am I following correctly?

**Comment by Nashatyrev** [comment] 2020-07-01 14:30
Another observation: `ValidatorDuties.Duties` instance is created with invalid `attestationSlot`. This time the slot was not previous to the correct one but a dozen of slots away. 
Will continue observations...

**Comment by Nashatyrev** [comment] 2020-07-01 17:09
https://github.com/PegaSysEng/teku/blob/b895c2553d3b5ee0c5c1876eecde339ce6a6c433/validator/coordinator/src/main/java/tech/pegasys/teku/validator/coordinator/ValidatorApiHandler.java#L124-L129

Can it be the reason: 
when we are calculating new duties (I guess this is done on epoch boundary) the latest block `N` in the previous epoch is not yet processed, so the `getLatestStateAtSlot()` returns us the state for the block `N-1`. We are getting the state `N'` via processing slots on top of the state `N-1` and submitting validator duty. After that the block `N` is finally received, the head state rebranches to `N` but the validator duty is not get rebranched and remains scheduled on a wrong head as if no block `N` exists.

**Comment by cemozerr** [comment] 2020-07-01 19:43
> Can it be the reason:

I think that is unlikely because looking at the logs, this issue happens 18 epochs in a row, which means that we'd have to have the scenario you've described 18 epochs in a row.  However, throughout those 18 epochs, we also don't seem to have the latest block at the correct time of the slot, so maybe that was still a possibility.

**Comment by ajsutton** [comment] 2020-07-01 23:12
There's two possibilities related to this - one is that we hadn't received and imported the block yet, the other is that we hadn't run fork choice to update our head.  The validator client should be recalculating it's duties if there's a reorg or if a block is imported from an epoch that would affect the calculations but it's possible that the "could it affect the duties" calculation is wrong or that we recalculate duties before fork choice runs to actually update the best head block so we wind up calculating the wrong duties again.

**Comment by Nashatyrev** [comment] 2020-07-02 10:07
I caught some cases with more info, below is one of them with debug info and my comments:

```java
00:48:52.152 INFO  - Slot Event  *** Slot: 127357, Block: d9a87d..53d9, Epoch: 3979, Finalized checkpoint: 3977, Finalized root: ba9b44..c304, Peers: 40
00:49:04.159 INFO  - Slot Event  *** Slot: 127358, Block:    ... empty, Epoch: 3979, Finalized checkpoint: 3977, Finalized root: ba9b44..c304, Peers: 40
00:49:16.176 INFO  - Slot Event  *** Slot: 127359, Block:    ... empty, Epoch: 3979, Finalized checkpoint: 3977, Finalized root: ba9b44..c304, Peers: 40
00:49:19.381 WARN  - Eth1 service down for 4621s, retrying
00:49:24.127 INFO  - Epoch Event *** Epoch: 3980, Justified checkpoint: 3978, Finalized checkpoint: 3977, Finalized root: ba9b44..c304
// we producing state for slot 127360 on top of existing head state for block 127358 by making slot transitions
// Our state for slot 127358 is the canonical state https://beaconcha.in/block/127358
ValidatorApiHandler.getDuties (line 128): latestState: 0x4c474059e2f9917d76f8192d9d08f28ffb3134d78a6887cbbb17479d4ce9cf39, 127358, for slot: 127360
// we are creating duties based on the state which is not canonical  (0xd5a8b1)
// since likely the block 127359 is imported later https://beaconcha.in/block/127359
ValidatorApiHandler.createValidatorDuties (line 303): committee=[26911, 10421, 5801,... , 11251, 21333, 1348], 3,127419
    state.hashTreeRoot()=0xd5a8b1fa71129ce95d494394ca057d3bbdf94c22a50a0018437b310fb11a8009
    epoch=3981, validatorIndex=1974
ValidatorApiDutyLoader.scheduleAttestationDuties: 127419, 1974
new AttestationProductionDuty: 127419
AttestationProductionDuty.addValidator: validatorIndex=1974, validatorPubKey=0xb6e880d58ec0d07a1490e65d3e38820d8dff3f093da8dacbb585cf884c403051def1544b7cda27870b90be4c8e53fea0
00:49:30.036 INFO  - Slot Event  *** Slot: 127360, Block: 53a13e..2b84, Epoch: 3980, Finalized checkpoint: 3978, Finalized root: 2aeb78..dfb3, Peers: 40
00:49:40.154 INFO  - Slot Event  *** Slot: 127361, Block: c1194b..51ee, Epoch: 3980, Finalized checkpoint: 3978, Finalized root: 2aeb78..dfb3, Peers: 40
{3=tech.pegasys.teku.validator.client.duties.AttestationProductionDuty$Committee@6d0683e2}
00:49:49.383 WARN  - Eth1 service down for 4651s, retrying
00:49:52.162 INFO  - Slot Event  *** Slot: 127362, Block: 805dc9..3830, Epoch: 3980, Finalized checkpoint: 3978, Finalized root: 2aeb78..dfb3, Peers: 40

[... skipped ...]

01:01:16.153 INFO  - Slot Event  *** Slot: 127419, Block:    ... empty, Epoch: 3981, Finalized checkpoint: 3979, Finalized root: 84ddf4..49f5, Peers: 40
{3=tech.pegasys.teku.validator.client.duties.AttestationProductionDuty$Committee@f85eb7f}
01:01:16.275 ERROR - Validator   *** Produced invalid attestation for slot 127419 with expected validator index: 12806 and actual validator index: 1974 . Invalid reason: Signature is invalid
```

So looks like we generated duties based on the non-canonical state and didn't regenerate them after reorg

**Comment by Nashatyrev** [comment] 2020-07-02 12:43
Another observation: 
```java
15:12:52.140 INFO  - Slot Event  *** Slot: 131677, Block: 697e08..85b9, Epoch: 4114, Finalized checkpoint: 4112, Finalized root: d0cf61..6ee8, Peers: 40
15:12:56.580 WARN  - Eth1 service down for 56438s, retrying
Importing block: SignedBeaconBlock{message=BeaconBlock{root=0x228faffc928c95c614753f970d030ea1dd1b7432ceeaab0fb5b2621fba25c371, slot=131678, proposer_index=26568, parent_root=0x697e0886f8bdc04091dc36e0a8e0a88c2674b10e544b3a75d5e64090d42385b9, state_root=0x171c9aeb6462ceaa11904a85fdb12ca4067dd0645f9c16226c538cdf12d471a7, body=0x95ca4da4e6c9e677d3835d8cba62348660c54e3b62bbe152a2035f1a6f944c86}, signature=0x892e07056e3b8159a0a2264c5243fd7101eb7dd6e58622ebb6a4b24a81a16aba385d46cba39c43f5ab8e96b310ec1b5c0e28ad9dc1215a5152e87efc5bc2e78ebea6342e5210d9d8661d13584d1b3c45d48a63fa723f75b042435f458c4e9299}
Importing block: SignedBeaconBlock{message=BeaconBlock{root=0x228faffc928c95c614753f970d030ea1dd1b7432ceeaab0fb5b2621fba25c371, slot=131678, proposer_index=26568, parent_root=0x697e0886f8bdc04091dc36e0a8e0a88c2674b10e544b3a75d5e64090d42385b9, state_root=0x171c9aeb6462ceaa11904a85fdb12ca4067dd0645f9c16226c538cdf12d471a7, body=0x95ca4da4e6c9e677d3835d8cba62348660c54e3b62bbe152a2035f1a6f944c86}, signature=0x892e07056e3b8159a0a2264c5243fd7101eb7dd6e58622ebb6a4b24a81a16aba385d46cba39c43f5ab8e96b310ec1b5c0e28ad9dc1215a5152e87efc5bc2e78ebea6342e5210d9d8661d13584d1b3c45d48a63fa723f75b042435f458c4e9299}
Imported block: SignedBeaconBlock{message=BeaconBlock{root=0x228faffc928c95c614753f970d030ea1dd1b7432ceeaab0fb5b2621fba25c371, slot=131678, proposer_index=26568, parent_root=0x697e0886f8bdc04091dc36e0a8e0a88c2674b10e544b3a75d5e64090d42385b9, state_root=0x171c9aeb6462ceaa11904a85fdb12ca4067dd0645f9c16226c538cdf12d471a7, body=0x95ca4da4e6c9e677d3835d8cba62348660c54e3b62bbe152a2035f1a6f944c86}, signature=0x892e07056e3b8159a0a2264c5243fd7101eb7dd6e58622ebb6a4b24a81a16aba385d46cba39c43f5ab8e96b310ec1b5c0e28ad9dc1215a5152e87efc5bc2e78ebea6342e5210d9d8661d13584d1b3c45d48a63fa723f75b042435f458c4e9299}
15:13:04.152 INFO  - Slot Event  *** Slot: 131678, Block: 228faf..c371, Epoch: 4114, Finalized checkpoint: 4112, Finalized root: d0cf61..6ee8, Peers: 40
{5=tech.pegasys.teku.validator.client.duties.AttestationProductionDuty$Committee@6a26fb29}
// No yet block 131679 so the head state is generated atop of block 131678
15:13:16.153 INFO  - Slot Event  *** Slot: 131679, Block:    ... empty, Epoch: 4114, Finalized checkpoint: 4112, Finalized root: d0cf61..6ee8, Peers: 40
Importing block: SignedBeaconBlock{message=BeaconBlock{root=0xb37865ebafd4b4620be6042901108a562ca78ce5b70aaf7db3c5e573c64a20b7, slot=131679, proposer_index=4950, parent_root=0x228faffc928c95c614753f970d030ea1dd1b7432ceeaab0fb5b2621fba25c371, state_root=0x7401873c0412e6adc15c2d35a317af41d6d27a983398abfcb8c5c7d850b8fc96, body=0x7b17976b56409d7ea393b425d04c784d3dda372013c61fbef2af569a0314aba9}, signature=0xa042e4e713bd251dcb6bcb0952008dc3d35b93e63af2ee7a3b23e63eee517c727138d539eb0283121506e46fd880d5a20a314230bc7ee77e74c7ae32a22cd2e800b9873fa8d6f42fd35e71c72cf492d659a82706468184a13a9be2beb54872fc}
// received and imported block 131679
Imported block: SignedBeaconBlock{message=BeaconBlock{root=0xb37865ebafd4b4620be6042901108a562ca78ce5b70aaf7db3c5e573c64a20b7, slot=131679, proposer_index=4950, parent_root=0x228faffc928c95c614753f970d030ea1dd1b7432ceeaab0fb5b2621fba25c371, state_root=0x7401873c0412e6adc15c2d35a317af41d6d27a983398abfcb8c5c7d850b8fc96, body=0x7b17976b56409d7ea393b425d04c784d3dda372013c61fbef2af569a0314aba9}, signature=0xa042e4e713bd251dcb6bcb0952008dc3d35b93e63af2ee7a3b23e63eee517c727138d539eb0283121506e46fd880d5a20a314230bc7ee77e74c7ae32a22cd2e800b9873fa8d6f42fd35e71c72cf492d659a82706468184a13a9be2beb54872fc}
15:13:24.122 INFO  - Epoch Event *** Epoch: 4115, Justified checkpoint: 4113, Finalized checkpoint: 4112, Finalized root: d0cf61..6ee8
// however duties are generated atop of block 131678 state
getDuties: latestState: 0x171c9aeb6462ceaa11904a85fdb12ca4067dd0645f9c16226c538cdf12d471a7, 131678, for slot: 131680
createValidatorDuties: [28564, 18255, 13027, 28049, 28882, 5841, 17508, 17385, 18968, 7343, 9556, 5601, 15378, 17430, 27745, 21579, 27064, 27754, 18023, 26646, 1974, 16423, 2511, 17909, 27172, 1274, 11436, 15386, 15669, 3268, 24260, 14457, 23294, 16044, 8446, 23678, 24245, 19756, 12978, 5184, 10114, 8194, 18569, 9684, 11696, 28209, 13353, 28788, 5650, 3997, 2923, 7594, 212, 141, 677, 21904, 18779, 27142, 27635, 29636, 20206, 3561, 19162, 13620, 28541, 27479, 13404, 20537, 2901, 1877, 12216, 4383, 19886, 25574, 26949, 10175, 15285, 759, 6586, 22340, 527, 21075, 12752, 28275, 13240, 1628, 9388, 12948, 18055, 25960, 19590, 14020, 6303, 12079, 17491, 2569, 8369, 23455, 18440, 3439, 12149, 29464, 12420, 9634, 14406, 28475, 27906, 1249, 20128, 20023, 20602, 22078, 125, 6137, 506, 18334, 8639, 902, 19846, 13630, 16178, 8324, 2300, 21701, 1436, 26409, 875, 5084, 26550, 4988, 10886, 27302, 11334], 3,131718
0x7939d93bcf43c96178419ca48dbe7774f6d8d98dcc489ca5f2fe0ba2efa46303
4116, 1974
scheduleAttestationDuties: 131718, 1974
new AttestationProductionDuty: 131718
```

**Comment by cemozerr** [comment] 2020-07-02 16:57
Let's assume the last slot of the epoch is 40. This is where we'll calculate the future epoch duties. We don't receive the latest block on time in this slot, so during `processHead()` our `chainHead` gets updated again with block and state of slot 39. (i.e. it doesn't change). After `processHead()` is completed, during the same slot, we do receive the block for slot 40. It just arrived a bit late.

At slot 41, we should normally see that there was indeed a block for slot 40, and thus we should re-calculate the block duties accordingly. For that, we need to be able to detect the "reorg". 

So at slot 41, 4 seconds into the slot, `processHead` runs again. This time we update the `chainHead` to the latest block and state at slot 41. We also save the previous chain head root and slot to check if they are ancestors of the new chain head. 

The problem is, the previous chain head slot is obtained from the `chainHead` object, which retrieves slot information from block slot. So we compare the previous chain head root with the ancestor of the new chain head root at slot 39, instead of comparing with the ancestor at 40. We should have gotten the ancestor of the new chain head at slot 40 and compared that with the previous chain head root instead. 

Thus, we don't detect the re-org. [insert-mic-drop-emoji]

**Comment by cemozerr** [comment] 2020-07-02 17:05
I have a feeling that the best way to solve this would be to make the current `chainHead` variable in `RecentChainData` redundant and use `ProtoArray` to get the `chainHead` information in constant time.

**Comment by Nashatyrev** [comment] 2020-07-02 18:14
@cemozerr Yep this is exactly what I see in debugger now. Waiting for your potential fix to confirm 👍

**Comment by Nashatyrev** [comment] 2020-07-02 19:00
From my perspective this should be definitely treated as chain reorg. 
```
[Block 39] --> [40]
     \-------> [Block 40] --> [Block 41]
```
So in this example our previous `head` state was `[40]` (i.e. a state with just slot transition from `[Block 39]` state), but then the head has changed to the state `[Block 40]` (slot transition + block) and then to `[Block 41]` 
```

**Comment by cemozerr** [comment] 2020-07-22 15:06
Reopening this issue as it seems to have started occurring again for each validator once every 24 hours on my Altona node.

**Comment by cemozerr** [comment] 2020-07-23 15:54
Closing this as the error I saw on my Altona node was due to the failed updating of my Teku node, and with the new version I haven't been seeing this error again.

**Closed as completed by cemozerr** 2020-07-23 15:54 UTC
Labels: bug 🐞, P1
