### ISSUE TITLE
Builder Profit Threshold [feature-request]

### ISSUE THREAD

**Issue by PizBernina** [Consensys-Incorporated/teku#6344] opened 2022-10-26 15:03 UTC
### Description
Would you be able to add a flag like that? https://lighthouse-book.sigmaprime.io/builders.html#builder-profit-threshold
From the lighthouse docs:
"--builder-profit-threshold <WEI_VALUE>
The number provided indicates the minimum reward that an external payload must provide the proposer for it to be considered for inclusion in a proposal. For example, if you'd only like to use an external payload for a reward of >= 0.25 ETH, you would provide your beacon node with --builder-profit-threshold 250000000000000000."

**Comment by PizBernina** [comment] 2022-10-26 15:06
mev-boost team is currently also working on a min-bid feature. In that sense, this feature-request would become obsolete (probably?)

**Comment by benjaminion** [comment] 2022-10-26 15:37
This looks to be a duplicate of #6140.

That one was closed because the general view (ours and the user who raised it) is that the right place for this functionality to be implemented is within MEV-Boost.

I'll discuss again with the team and leave this open meanwhile, but it's likely that we will defer this to MEV-Boost's implementation.

**Comment by tbenr** [comment] 2022-10-27 08:16
this has been already implemented in mev-boost https://github.com/flashbots/mev-boost/pull/274 and will be included in the next release (latest RC already have it)

**Closed as completed by tbenr** 2022-10-27 08:16 UTC
