### ISSUE TITLE
Nethermind+Teku: Cannot create attestation for future slot.

### ISSUE THREAD

**Issue by alundkvist** [Consensys-Incorporated/teku#6219] opened 2022-09-16 07:15 UTC
I am experiencing missed attestations with Nethermind+Teku. I see this in the log:

2022-09-16 06:57:55.126 ERROR - Validator *** Failed to produce attestation Slot: 4707287 Validator: b3d02ea, b00f5ad, 8254c49
java.lang.IllegalArgumentException: Invalid params response from Beacon Node API (url = http://beacon-chain.teku.dappnode:3500/eth/v1/validator/attestation_data?slot=4707287&committee_index=3, status = 400, message = Cannot create attestation for future slot. Requested 4707287 but current slot is 4707285)
at tech.pegasys.teku.validator.remote.apiclient.ResponseHandler.defaultBadRequestHandler(ResponseHandler.java:110) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.validator.remote.apiclient.ResponseHandler.handleResponse(ResponseHandler.java:71) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.executeCall(OkHttpValidatorRestApiClient.java:422) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.get(OkHttpValidatorRestApiClient.java:367) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.get(OkHttpValidatorRestApiClient.java:353) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.validator.remote.apiclient.OkHttpValidatorRestApiClient.createAttestationData(OkHttpValidatorRestApiClient.java:213) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$createAttestationData$10(RemoteValidatorApiHandler.java:251) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:81) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.sendRequest(RemoteValidatorApiHandler.java:460) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.validator.remote.RemoteValidatorApiHandler.lambda$sendRequest$32(RemoteValidatorApiHandler.java:455) ~[teku-validator-remote-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:73) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-22.9.0.jar:22.9.0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
at java.lang.Thread.run(Unknown Source) ~[?:?]

**Comment by alundkvist** [comment] 2022-09-16 07:25
Teku beacon-chain has 100 peers, and I don't see anything in the logs indicating that the beacon-chain should be slow.

**Comment by ajsutton** [comment] 2022-09-16 09:05
Thanks for raising - I believe this is a duplicate of #6016. It's a key symptom of the performance issues we've been digging into as our top priority.  We're seeing good results on our nodes from some fixes we've got so far.  At the moment there's not really much you can do beyond providing as much IO speed as possible and staying tuned for updates in our discord.

Will close this in favour of #6016 so we don't lose track of things.

**Closed as completed by ajsutton** 2022-09-16 09:05 UTC
