### ISSUE TITLE
Failure to recover after network outtage: ProtoArray: Best node is not viable for head

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#3842] opened 2021-04-09 05:13 UTC
Version: `teku/v21.3.2/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13`

I had a 2 hour internet outage. After the network recovered, Teku regained peers but was unable to import blocks or produce attestations. This lasted 4 hours until I restarted Teku, which successfully restored normal functioning.

This is the network going down:

```
23:10:03.157 INFO  - ^[[37mSlot Event  *** Slot: 924948, Block: a630f3..d23a, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 100^[[0m
23:10:15.160 INFO  - ^[[37mSlot Event  *** Slot: 924949, Block: 6780ce..77eb, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 100^[[0m
23:10:23.358 INFO  - ^[[34mValidator   *** Published attestation  Count: 1, Slot: 924950, Root: 10ba31..4275^[[0m
23:10:27.159 INFO  - ^[[37mSlot Event  *** Slot: 924950, Block: 10ba31..4275, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 100^[[0m
23:10:31.005 INFO  - ^[[34mValidator   *** Published aggregate    Count: 1, Slot: 924950, Root: 10ba31..4275^[[0m
23:10:39.159 INFO  - ^[[37mSlot Event  *** Slot: 924951, Block: 5eaa67..05eb, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 100^[[0m
23:10:51.159 INFO  - ^[[37mSlot Event  *** Slot: 924952, Block:    ... empty, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 100^[[0m
23:11:03.183 INFO  - ^[[37mSlot Event  *** Slot: 924953, Block:    ... empty, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 100^[[0m
23:11:15.154 INFO  - ^[[37mSlot Event  *** Slot: 924954, Block:    ... empty, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 94^[[0m
23:11:27.154 INFO  - ^[[37mSlot Event  *** Slot: 924955, Block:    ... empty, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 0^[[0m
23:11:39.154 INFO  - ^[[37mSlot Event  *** Slot: 924956, Block:    ... empty, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 0^[[0m
23:11:51.154 INFO  - ^[[37mSlot Event  *** Slot: 924957, Block:    ... empty, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 0^[[0m
23:12:03.153 INFO  - ^[[37mSlot Event  *** Slot: 924958, Block:    ... empty, Epoch: 28904, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 0^[[0m
```

This is the network coming back:

```
01:02:03.145 INFO  - ^[[37mSlot Event  *** Slot: 925508, Block:    ... empty, Epoch: 28922, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 0^[[0m
01:02:15.145 INFO  - ^[[37mSlot Event  *** Slot: 925509, Block:    ... empty, Epoch: 28922, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 0^[[0m
01:02:24.592 WARN  - Eth1 service down for 6630s, retrying
01:02:27.152 INFO  - ^[[37mSlot Event  *** Slot: 925510, Block:    ... empty, Epoch: 28922, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 9^[[0m
01:02:27.628 INFO  - Chain reorg at slot 925510 from 5eaa67..05eb to dee39e..4448. Common ancestor at slot 924951
01:02:27.692 INFO  - Chain reorg at slot 925510 from dee39e..4448 to d89be5..45e0. Common ancestor at slot 924953
01:02:27.736 INFO  - Chain reorg at slot 925510 from d89be5..45e0 to 504354..e999. Common ancestor at slot 924954
01:03:16.121 INFO  - ^[[37mMiss slots  *** Current slot: 925514, previous slot: 925511^[[0m
01:03:16.145 INFO  - Chain reorg at slot 925510 from 504354..e999 to dcf590..2aca. Common ancestor at slot 924955
01:03:16.220 INFO  - ^[[37mSlot Event  *** Slot: 925514, Block:    ... empty, Epoch: 28922, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 9^[[0m
01:03:16.754 INFO  - Chain reorg at slot 925514 from dcf590..2aca to db5519..9d96. Common ancestor at slot 924956
01:03:19.010 INFO  - Chain reorg at slot 925514 from db5519..9d96 to 4e0b80..153a. Common ancestor at slot 924957
01:04:05.452 INFO  - ^[[37mMiss slots  *** Current slot: 925518, previous slot: 925515^[[0m
01:04:05.499 INFO  - ^[[37mSlot Event  *** Slot: 925518, Block:    ... empty, Epoch: 28922, Finalized checkpoint: 28902, Finalized root: 802403..11fa, Peers: 21^[[0m
01:04:05.579 INFO  - Chain reorg at slot 925518 from 4e0b80..153a to 0d09be..16d8. Common ancestor at slot 924958
01:04:08.422 INFO  - Completed regeneration of block 0xb0ac3446b81b49197f81537bc3b5277024696c5f96fdbd74994fc7ed7b8fc311 at slot 924896 by replaying 30 blocks. Took 1027ms
01:04:08.668 INFO  - Chain reorg at slot 925518 from 0d09be..16d8 to c6a81e..4b8b. Common ancestor at slot 924959
01:04:09.861 INFO  - Chain reorg at slot 925518 from c6a81e..4b8b to 8e7a58..f043. Common ancestor at slot 924960
01:04:53.174 INFO  - ^[[37mMiss slots  *** Current slot: 925522, previous slot: 925519^[[0m
01:04:53.975 INFO  - Completed regeneration of block 0xbc092565a7f709b22a18ed92190340d2b098704014ff2bab550c021f3375afd3 at slot 924928 by replaying 4 blocks. Took 797ms
01:04:53.976 INFO  - Chain reorg at slot 925518 from 8e7a58..f043 to 0591e5..131d. Common ancestor at slot 924961
01:04:54.058 INFO  - ^[[37mSlot Event  *** Slot: 925522, Block:    ... empty, Epoch: 28922, Finalized checkpoint: 28903, Finalized root: b0ac34..c311, Peers: 29^[[0m
01:04:58.360 INFO  - Chain reorg at slot 925522 from 0591e5..131d to 7359d8..f740. Common ancestor at slot 924962
01:04:59.456 INFO  - Chain reorg at slot 925522 from 7359d8..f740 to 81de26..4849. Common ancestor at slot 924963
01:05:43.861 INFO  - ^[[37mMiss slots  *** Current slot: 925526, previous slot: 925523^[[0m
01:05:43.904 INFO  - ^[[37mSlot Event  *** Slot: 925526, Block:    ... empty, Epoch: 28922, Finalized checkpoint: 28903, Finalized root: b0ac34..c311, Peers: 41^[[0m
01:05:43.943 INFO  - Chain reorg at slot 925526 from 81de26..4849 to c273d4..4cde. Common ancestor at slot 924964
01:05:47.255 INFO  - Chain reorg at slot 925526 from c273d4..4cde to f0718c..6aa4. Common ancestor at slot 924965
01:05:51.161 INFO  - Chain reorg at slot 925526 from f0718c..6aa4 to a9c9c5..edba. Common ancestor at slot 924966
01:05:51.216 INFO  - ^[[37mSlot Event  *** Slot: 925527, Block:    ... empty, Epoch: 28922, Finalized checkpoint: 28903, Finalized root: b0ac34..c311, Peers: 40^[[0m
01:06:32.776 INFO  - ^[[37mSync Event  *** Current slot: 925528, Head slot: 924967, Connected peers: 43^[[0m
01:06:32.862 INFO  - ^[[37mSync Event  *** Current slot: 925529, Head slot: 924968, Connected peers: 43^[[0m
01:06:32.924 INFO  - ^[[37mSync Event  *** Current slot: 925530, Head slot: 924969, Connected peers: 43^[[0m
01:06:35.451 INFO  - ^[[37mSync Event  *** Current slot: 925531, Head slot: 924992, Connected peers: 45^[[0m
01:06:47.381 INFO  - ^[[37mSync Event  *** Current slot: 925532, Head slot: 925167, Connected peers: 49^[[0m
01:06:59.351 INFO  - ^[[37mSync Event  *** Current slot: 925533, Head slot: 925358, Connected peers: 48^[[0m
01:07:05.623 INFO  - Chain reorg at slot 925533 from f714ed..67bb to 9c9893..f186. Common ancestor at slot 925440
01:07:05.658 INFO  - Chain reorg at slot 925533 from 9c9893..f186 to f62ceb..c93e. Common ancestor at slot 925441
01:07:05.722 INFO  - Chain reorg at slot 925533 from f62ceb..c93e to 673796..89f5. Common ancestor at slot 925442
01:07:06.393 INFO  - Chain reorg at slot 925533 from 673796..89f5 to 6695bd..9b1b. Common ancestor at slot 925443
01:07:07.146 INFO  - Chain reorg at slot 925533 from 6695bd..9b1b to 9f3eb6..28a6. Common ancestor at slot 925444
01:07:07.795 INFO  - Chain reorg at slot 925533 from 9f3eb6..28a6 to a79551..5de6. Common ancestor at slot 925445
01:07:08.374 INFO  - Chain reorg at slot 925533 from a79551..5de6 to b7ace9..e737. Common ancestor at slot 925446
01:07:08.742 INFO  - Chain reorg at slot 925533 from b7ace9..e737 to 640ac6..227c. Common ancestor at slot 925447
01:07:09.388 INFO  - Chain reorg at slot 925533 from 640ac6..227c to 523461..d8d0. Common ancestor at slot 925448
01:07:09.969 INFO  - Chain reorg at slot 925533 from 523461..d8d0 to e070b5..81d4. Common ancestor at slot 925449
01:07:10.398 INFO  - Chain reorg at slot 925533 from e070b5..81d4 to 9b19c7..20b4. Common ancestor at slot 925450
01:07:10.968 INFO  - Chain reorg at slot 925533 from 9b19c7..20b4 to fcd91a..77e7. Common ancestor at slot 925451
01:07:11.551 INFO  - Chain reorg at slot 925533 from fcd91a..77e7 to c4ea8b..38c9. Common ancestor at slot 925452
01:07:12.274 INFO  - Chain reorg at slot 925533 from c4ea8b..38c9 to b198df..84fe. Common ancestor at slot 925453
01:07:12.350 INFO  - Chain reorg at slot 925533 from b198df..84fe to 5e4ada..b395. Common ancestor at slot 925454
01:07:12.862 INFO  - Chain reorg at slot 925533 from 5e4ada..b395 to eebcee..4f98. Common ancestor at slot 925455
01:07:13.578 INFO  - Chain reorg at slot 925533 from eebcee..4f98 to cfdc22..24f5. Common ancestor at slot 925456
01:07:14.368 INFO  - Chain reorg at slot 925533 from cfdc22..24f5 to a63c2c..2352. Common ancestor at slot 925457
01:07:14.718 ERROR - Internal error while importing block: a63c2c..2352 (925458)
java.util.concurrent.CompletionException: java.lang.RuntimeException: ProtoArray: Best node is not viable for head
        at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1093) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2159) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.lambda$propagateResult$3(SafeFuture.java:142) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883) ~[?:?]
        at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2322) ~[?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:501) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.whenComplete(SafeFuture.java:29) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateResult(SafeFuture.java:139) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.propagateTo(SafeFuture.java:236) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.ScheduledExecutorAsyncRunner.lambda$createRunnableForAction$1(ScheduledExecutorAsyncRunner.java:119) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.RuntimeException: ProtoArray: Best node is not viable for head
        at tech.pegasys.teku.protoarray.ProtoArray.findHead(ProtoArray.java:175) ~[teku-protoarray-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.protoarray.ForkChoiceStrategy.findHead(ForkChoiceStrategy.java:94) ~[teku-protoarray-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.findNewChainHead(ForkChoice.java:254) ~[teku-ethereum-statetransition-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.updateForkChoiceForImportedBlock(ForkChoice.java:225) ~[teku-ethereum-statetransition-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.statetransition.forkchoice.ForkChoice.lambda$onBlock$4(ForkChoice.java:197) ~[teku-ethereum-statetransition-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.recordEventThreadIdAndExecute(AsyncRunnerEventThread.java:109) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.eventthread.AsyncRunnerEventThread.lambda$doExecute$1(AsyncRunnerEventThread.java:92) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:78) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.AsyncRunner.lambda$runAsync$2(AsyncRunner.java:38) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.of(SafeFuture.java:70) ~[teku-infrastructure-async-21.3.2.jar:21.3.2]
        ... 4 more
01:07:14.972 INFO  - Chain reorg at slot 925533 from a63c2c..2352 to 9486d5..c6b4. Common ancestor at slot 925458
01:07:15.771 INFO  - Chain reorg at slot 925533 from 9486d5..c6b4 to 58fbc7..d8bb. Common ancestor at slot 925459
```

After many more reorgs and one more instance of the same exception, no blocks are imported and attestation production sometimes, but not always, fails with a slashing protection exception.  The main point is that all slots are shown as empty until the restart.

```
01:38:15.154 INFO  - ^[[37mSlot Event  *** Slot: 925689, Block:    ... empty, Epoch: 28927, Finalized checkpoint: 28923, Finalized root: 9fea93..6ca1, Peers: 100^[[0m
01:38:27.156 INFO  - ^[[37mSlot Event  *** Slot: 925690, Block:    ... empty, Epoch: 28927, Finalized checkpoint: 28923, Finalized root: 9fea93..6ca1, Peers: 100^[[0m
01:38:39.156 INFO  - ^[[37mSlot Event  *** Slot: 925691, Block:    ... empty, Epoch: 28927, Finalized checkpoint: 28923, Finalized root: 9fea93..6ca1, Peers: 99^[[0m
01:38:51.156 INFO  - ^[[37mSlot Event  *** Slot: 925692, Block:    ... empty, Epoch: 28927, Finalized checkpoint: 28923, Finalized root: 9fea93..6ca1, Peers: 99^[[0m
01:38:51.216 ERROR - Refusing to sign attestation:  source epoch (28924) is safe, target epoch (28927) is unsafe.  Previously signed source epoch 28922, target epoch 28927
01:38:51.220 ERROR - ^[[31mValidator   *** Failed to produce attestation  Slot: 925692 Validator: 0x<redacted>^[[0m
tech.pegasys.teku.core.signatures.SlashableConditionException: Refusing to sign attestation at slot 925692 with source epoch 28924 and target epoch 28927 because it may violate a slashing condition
```

I can provide the full log file if useful.

**Comment by ajsutton** [comment] 2021-04-14 01:39
Can confirm that this is a duplicate of #3793 which we've fixed with #3797.

**Closed as completed by ajsutton** 2021-04-14 01:39 UTC
