### ISSUE TITLE
ForkChoiceTest failing intermittently

### ISSUE THREAD

**Issue by mbaxter** [Consensys-Incorporated/teku#2698] opened 2020-08-31 14:53 UTC
### Description
It looks like `ForkChoiceTest` is failing intermittently.  We should look into these failures.  See:
- https://app.circleci.com/pipelines/github/PegaSysEng/teku/6616/workflows/bcf8722e-dd23-44e9-b853-14a52b7fb30d/jobs/41573
- https://app.circleci.com/pipelines/github/PegaSysEng/teku/6534/workflows/5262e966-6230-468c-a446-d3ca94a2c3c7/jobs/41059

**Comment by ajsutton** [comment] 2020-08-31 21:05
Duplicate of #2699.

**Closed as completed by ajsutton** 2020-08-31 21:05 UTC
Labels: bug 🐞
