### ISSUE TITLE
Boolean CLI options are not displaying default values

### ISSUE THREAD

**Issue by bgravenorst** [Consensys-Incorporated/teku#1753] opened 2020-05-10 21:34 UTC
### Description
As user, I want view the default values for CLI options so that I can easily see which options
I need to enable or disable. 

Currently running `teku --help` does not display the default values for boolean CLI options.

**Comment by ajsutton** [comment] 2020-05-11 00:57
This looks like a duplicate of #1746.

**Closed as completed by ajsutton** 2020-05-11 00:57 UTC
