### ISSUE TITLE
change to voluntary exits for deneb

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6942] opened 2023-03-14 01:21 UTC
Basically looking at simplifying voluntary exits so they're not only valid for 2 forks...

Slated for Deneb if approved and merged.

https://github.com/ethereum/consensus-specs/pull/3288

**Comment by StefanBratanov** [comment] 2023-06-20 15:41
Closed as duplicate of #7262

**Closed as completed by StefanBratanov** 2023-06-20 15:41 UTC
Labels: Epic Deneb
