### ISSUE TITLE
Zinken: Restarting beacon complains about existing lock file

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#2910] opened 2020-10-07 20:14 UTC
Zinken before genesis state has been calculated. A lock file is created; stopping and restarting the beacon will have the beacon exit because of the existing lock file. This is the lock file for avoiding running two validators on the same key, I believe,

```
yorick@ethlinux:~/eth2-zinken-teku$ docker-compose down
Stopping eth2-zinken-teku_geth_1 ... done
Removing eth2-zinken-teku_geth_1 ... done
Removing network eth2-zinken-teku_default
yorick@ethlinux:~/eth2-zinken-teku$ docker-compose up -d eth2
Creating network "eth2-zinken-teku_default" with the default driver
Creating eth2-zinken-teku_geth_1 ... done
Creating eth2-zinken-teku_beacon_1 ... done
Creating eth2-zinken-teku_eth2_1   ... done
yorick@ethlinux:~/eth2-zinken-teku$ docker-compose logs -f beacon
Attaching to eth2-zinken-teku_beacon_1
beacon_1            | 2020-10-07 20:11:47,631 main INFO Setting logging level to INFO
beacon_1            | 2020-10-07 20:11:48,478 main INFO Configuring logging for destination: console
beacon_1            | 2020-10-07 20:11:48,479 main INFO Logging includes events: true
beacon_1            | 2020-10-07 20:11:48,480 main INFO Logging includes validator duties: true
beacon_1            | 2020-10-07 20:11:48,487 main INFO Logging includes color: true
beacon_1            | 20:11:48.530 INFO  - Teku version: teku/v0.12.10-dev-f8fbf9fa/linux-x86_64/oracle_openjdk-java-14
beacon_1            | 20:11:49.735 INFO  - Loading 1 validator keys...
beacon_1            | Keystore file /var/lib/teku/validator-keys/keystore-m_12381_3600_2_0_0-1601727363.json.lock already in use.
beacon_1            |
beacon_1            | To display full help:
beacon_1            | teku [COMMAND] --help
eth2-zinken-teku_beacon_1 exited with code 1
```

**Comment by ajsutton** [comment] 2020-10-07 22:15
Thanks for reporting this, we'll need to investigate further, but it looks like Docker has terminated the teku process without giving it a chance to release lock files.

You can disable the use of lock files with `--validators-keystore-locking-enabled false` as a temporary work around.

**Comment by yorickdowne** [comment] 2020-10-07 22:32
Looking at what docker-compose does, it's possible the beacon exited abnormally, and this ended up NOT being a regular restart thereby.

I have since restarted teku a few times, and it did not exhibit this behavior.

**Comment by cemozerr** [comment] 2020-10-09 20:36
Hi @yorickdowne, we've looked into this issue, and we were only able to reproduce this scenario when the container running Teku was killed. 

Inside the docker container, Teku does not have access to the process PID. This means that Teku can't save its process PID into the lock file. So if it's killed abruptly, (like when the docker container is killed) it can't delete the lock file. Later on during restart, since it does not have the process PID in the lockfile, it can't clean up the lockfile. Thus, it hits this issue.

With normal stops and restarts to the container, cleaning the lock file is not an issue. Thus I'm closing this ticket. Let us know if you have other issues!

**Closed as completed by cemozerr** 2020-10-09 20:36 UTC
Labels: bug 🐞, P2
