### ISSUE TITLE
Remote access to the metrics port seems broken

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2210] opened 2020-06-24 12:07 UTC
Report from @tzapu:

> got a problem with teku that seems eerily similar to one i had with eth2signer ( https://github.com/PegaSysEng/eth2signer/issues/97 ) i'm running with

```
|       --metrics-enabled=true                                                                                                                                                    
│       --metrics-port=8008                                                                                                                                                       
│       --metrics-interface=0.0.0.0                                                                                                                                               
│       --metrics-host-allowlist=localhost, 127.0.0.1                                                                                                                             
```
> but getting server returned HTTP status 403 Forbidden  when trying to connect from outside the pod. seeing that i am getting 403 the port must be right.

I've also had truble with this. Using the options ` --metrics-enabled=true --metrics-host-allowlist='*' --rest-api-docs-enabled=true --rest-api-host-allowlist='*'` I can access the RPC port remotely (5051), but get a 403 from the metrics port (8008), which is unexpected. Explicitly putting my remote host's IP address in the allow list does not help.

Local access is working OK for me with the above options.

**Comment by cemozerr** [comment] 2020-06-24 20:42
Hi @tzapu,
Seems like Teku is actually showing expected behavior. To be able to connect from a remote host, you can use the option `--metrics-host-allowlist='*'` or  `--metrics-host-allowlist=<remote-host-ip>`.

**Comment by tzapu** [comment] 2020-06-24 20:57
@benjaminion tried with * and i think i tried as well before trying ` --metrics-host-allowlist=localhost, 127.0.0.1 ` like in eth2signer.
i will try again and report

**Comment by cemozerr** [comment] 2020-06-24 21:04
Seems like @benjaminion was missing the `--metrics-interface` option. To be able to connect to Teku metrics from a remote host, that has to be set to `0.0.0.0`, as well as `--metrics-host-allowlist` has to be set to `'*'` or `<remote-host-ip>`

**Comment by tzapu** [comment] 2020-06-24 21:06
bingo, it was the bloody quotes 🤦🏻‍♂️
i had `--metrics-host-allowlist=*` before, which  doesn't  work, but `--metrics-host-allowlist="*"` DOES!

thank you Cem and Ben

**Comment by cemozerr** [comment] 2020-06-24 21:07
My pleasure! Will keep the issue on until we figure @benjaminion's issue as well, but glad you figured it out.

**Comment by cemozerr** [comment] 2020-06-24 21:35
@benjaminion seems like, for your case, you were missing the `--metrics-interface=0.0.0.0`, which would have made Teku metrics visible to remote hosts. The only reason Rest API worked without `--rest-api-interface=0.0.0.0`, is because of this issue we apparently have: https://github.com/PegaSysEng/teku/issues/2213. So if you provide those flags, your metrics should be accessible from remote hosts. Closing this issue as I'm pretty sure that will fix your problem, but let me know and we can open it up again.

**Closed as completed by cemozerr** 2020-06-24 21:35 UTC
