### ISSUE TITLE
[API] add `payload_attributes` to eventStream events

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#7477] opened 2023-09-03 21:55 UTC

**Comment by rolfyone** [comment] 2023-09-05 03:43
https://ethereum.github.io/beacon-APIs/#/Events/eventstream

It looks like the event stream `payload_attributes` is fairly well defined, it sounds like it is wanted at the same time that we send FcU or there abouts, with withdrawals etc so that block builders can build on the chain.

We probably need to get a good idea of where in the flow this fits, so we can send these messages at the correct time.

The fact that withdrawals is included is why I think maybe somewhere close to fork choice updated messages that go to the EL.

**Comment by StefanBratanov** [comment] 2023-12-18 16:04
Duplicate of #6817

**Closed as completed by StefanBratanov** 2023-12-18 16:04 UTC
