### ISSUE TITLE
Segfault on Fedora 32, Java 15, OpenJDK 20.9

### ISSUE THREAD

**Issue by michaelsproul** [Consensys-Incorporated/teku#3125] opened 2020-11-02 07:25 UTC
### Description

My Teku node segfaulted while syncing from genesis.

```
16:08:57.993 INFO  - Sync Event  *** Current slot: 645644, Head slot: 47776, Connected peers: 28
16:09:10.817 INFO  - Sync Event  *** Current slot: 645645, Head slot: 47808, Connected peers: 27
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fa160cb3b31, pid=210481, tid=211314
#
# JRE version: OpenJDK Runtime Environment 20.9 (15.0+36) (build 15+36)
# Java VM: OpenJDK 64-Bit Server VM 20.9 (15+36, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xd8fb31]  ObjectSynchronizer::get_lock_owner(ThreadsList*, Handle)+0x51
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/michael/teku-medalla/core.210481)
#
# An error report file with more information is saved as:
# /home/michael/teku-medalla/hs_err_pid210481.log
Compiled method (n/a) 12689402 20398     n 0       sun.management.ThreadImpl::getThreadInfo1 (native)
 total in heap  [0x00007fa148ba4a90,0x00007fa148ba4e18] = 904
 relocation     [0x00007fa148ba4be8,0x00007fa148ba4c20] = 56
 main code      [0x00007fa148ba4c20,0x00007fa148ba4e18] = 504
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-latest-openjdk&version=32
#
./teku.sh: line 9: 210481 Aborted                 (core dumped) ./teku-0.12.12/bin/teku --network=medalla --rest-api-enabled --rest-api-docs-enabled --metrics-enabled
```

### Steps to Reproduce

Unsure, looks like some kind of race condition, or possibly a bug in the JVM. If it happens again I'll likely try a different JVM version.

I was running with these arguments:

```
#!/bin/bash

export JAVA_OPTS="-Xmx2g"

./teku-0.12.12/bin/teku \
    --network=medalla \
    --rest-api-enabled \
    --rest-api-docs-enabled \
    --metrics-enabled
```

### Versions

* Software version: `teku/v0.12.12/linux-x86_64/-redhatinc-openjdk64bitservervm-java-15`
* Java version:
```
openjdk version "15" 2020-09-15
OpenJDK Runtime Environment 20.9 (build 15+36)
OpenJDK 64-Bit Server VM 20.9 (build 15+36, mixed mode, sharing)
```
* OS Name & Version: `Fedora release 32 (Thirty Two)`
* Kernel Version: `Linux my-hostname 5.8.15-201.fc32.x86_64 #1 SMP Thu Oct 15 15:56:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Virtual Machine software & version: N/A
* Docker Version: N/A
* Cloud VM, type, size: N/A
* CPU: Core i3 530 (2010)

### Additional Information

This issue looks similar: https://github.com/ConsenSys/teku/issues/3079

**Comment by michaelsproul** [comment] 2020-11-02 09:56
Got another one within a few hours of restarting:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f7fd2123f34, pid=215814, tid=215834
#
# JRE version: OpenJDK Runtime Environment 20.9 (15.0+36) (build 15+36)
# Java VM: OpenJDK 64-Bit Server VM 20.9 (15+36, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x687f34]  oopDesc::size_given_klass(Klass*)+0x4
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/michael/teku-medalla/core.215814)
#
# An error report file with more information is saved as:
# /home/michael/teku-medalla/hs_err_pid215814.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-latest-openjdk&version=32
#
```

**Comment by rolfyone** [comment] 2020-11-02 23:00
Thanks for raising this, can we get a copy of the core dump? `/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h` ? It will help diagnosis...

**Comment by michaelsproul** [comment] 2020-11-03 00:00
Here are the crash logs from Java, and I'll DM you the core dump links in case there's any sensitive data in there (I wasn't running any validators, so there shouldn't be):

https://sproul.xyz/eth2/hs_err_pid210481.log
https://sproul.xyz/eth2/hs_err_pid215814.log

Btw, I'm running on Java 11 now without issue, so it must be something specific about the `java-latest-openjdk` package, although I guess Java 15 is OK for other users?

**Comment by michaelsproul** [comment] 2020-11-03 00:35
DMed on Telegram

**Comment by rolfyone** [comment] 2020-11-03 04:15
We've got a bunch on jvm 14, but this is the first i've seen with jvm15...

**Comment by benjaminion** [comment] 2020-11-03 07:24
Here's one from me on OpenJDK 13/Ubuntu 20.04
```
23:45:49.184 INFO  - Slot Event  *** Slot: 651228, Block:    ... empty, Epoch: 20350, Finalized checkpoint: 15614, Finalized root: b38064..b440, Peers: 80
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2cef94fa08, pid=229988, tid=230150
#
# JRE version: OpenJDK Runtime Environment (13.0.3+3) (build 13.0.3+3-Ubuntu-1ubuntu2)
# Java VM: OpenJDK 64-Bit Server VM (13.0.3+3-Ubuntu-1ubuntu2, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x474a08]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P %E" (or dumping to /data/teku_medalla/data/core.229988)
#
# An error report file with more information is saved as:
# /data/teku_medalla/data/hs_err_pid229988.log
Compiled method (n/a) 406960996 20571     n 0       sun.management.ThreadImpl::getThreadInfo1 (native)
 total in heap  [0x00007f2cd94c4490,0x00007f2cd94c4820] = 912
 relocation     [0x00007f2cd94c45f0,0x00007f2cd94c4620] = 48
 main code      [0x00007f2cd94c4620,0x00007f2cd94c4820] = 512
```

I have the coredump (only 60MB) and can provide it. I also have the *hs_err_pidNNN.log* file.

**Comment by ajsutton** [comment] 2020-11-06 04:15
Copying my comment from #3079 here: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8249871 looks extremely similar - the ThreadLocal.getMap method is called by ThreadLocal.remove and is also small enough to have likely been inlined. Unfortunately its still unresolved.

All of these reports are in an area which is accessing thread information in some form which points back to that same bug.

**Comment by ajsutton** [comment] 2020-11-17 00:28
I can reproduce the crash when reprocessing through the long period of non-finality on Medalla but only as the java heap becomes almost completely full.  Most likely the node would crash with `OutOfMemoryError` shortly anyway and providing extra memory seems to allow it to continue fine.

I'd definitely be interested in hearing from anyone seeing this issue more recently while the network is finalizing and/or when the heap isn't full.

Given it's slightly different to the other jdk bugs mentioned above, I've logged an issue with Oracle specifically for this which is currently in internal review (internal review ID : 9067712).

**Comment by ajsutton** [comment] 2020-11-17 07:01
Reproduced on bare metal.  Same medalla sync with -Xmx4g:
```
{"timestamp":"2020-11-17T06:40:45,015","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 754103, Head slot: 610663, Connected peers: 74","throwable":""}
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f70733783cc, pid=5024, tid=5085
#
# JRE version: OpenJDK Runtime Environment 20.3 (14.0.2+12) (build 14.0.2+12)
# Java VM: OpenJDK 64-Bit Server VM 20.3 (14.0.2+12, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x7053cc]  G1ParScanThreadState::copy_to_survivor_space(G1HeapRegionAttr, oopDesc*, markWord)+0x37c
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/teku/teku-develop/hs_err_pid5024.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora%20EPEL&component=java-latest-openjdk&version=epel7
#

```

**Comment by ajsutton** [comment] 2022-02-21 04:01
This hasn't been an ongoing issue and JDK versions have progressed a lot since. Given it only occurred when teku wouldn't be able to continue due to lack of memory anyway I'm going to close this.

**Closed as completed by ajsutton** 2022-02-21 04:01 UTC
Labels: bug 🐞, P3
