### ISSUE TITLE
Failure to open database after Teku upgrade

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#3893] opened 2021-04-21 12:41 UTC
Report from `stefa2k#3917` on Discord:

> got an issue when updating from 21.3.2 to 21.4.0.

I've requested the full version info: I believe that we have made some changes to the DB columns, but I don't think they are in a release yet. Note the `RocksDBException: You have to open all column families. Column families not opened:` message.

```
beacon_1         | 11:32:25.770 INFO  - Beacon data directory set to: /opt/teku/data/beacon
beacon_1         | 11:32:27.758 FATAL - Failed to open database at path: /opt/teku/data/beacon/archive
beacon_1         | tech.pegasys.teku.storage.server.DatabaseStorageException: Failed to open database at path: /opt/teku/data/beacon/archive
beacon_1         |      at tech.pegasys.teku.storage.server.DatabaseStorageException.unrecoverable(DatabaseStorageException.java:31) ~[teku-storage-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.storage.server.rocksdb.RocksDbExceptionUtil.wrapException(RocksDbExceptionUtil.java:23) ~[teku-storage-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstanceFactory.create(RocksDbInstanceFactory.java:110) ~[teku-storage-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.storage.server.rocksdb.RocksDbDatabase.createV4(RocksDbDatabase.java:130) ~[teku-storage-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.storage.server.VersionedDatabaseFactory.createV5Database(VersionedDatabaseFactory.java:242) ~[teku-storage-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.storage.server.VersionedDatabaseFactory.createDatabase(VersionedDatabaseFactory.java:151) ~[teku-storage-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.services.chainstorage.StorageService.lambda$doStart$0(StorageService.java:62) ~[teku-services-chainstorage-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.infrastructure.async.SafeFuture.fromRunnable(SafeFuture.java:151) ~[teku-infrastructure-async-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.services.chainstorage.StorageService.doStart(StorageService.java:49) ~[teku-services-chainstorage-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:33) ~[teku-services-serviceutils-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.services.ServiceController.doStart(ServiceController.java:29) ~[teku-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.service.serviceutils.Service.start(Service.java:33) ~[teku-services-serviceutils-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.AbstractNode.start(AbstractNode.java:83) ~[teku-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.Teku.start(Teku.java:46) ~[teku-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:282) [teku-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.cli.BeaconNodeCommand.call(BeaconNodeCommand.java:71) [teku-21.4.0.jar:21.4.0]
beacon_1         |      at picocli.CommandLine.executeUserObject(CommandLine.java:1933) [picocli-4.4.0.jar:4.4.0]
beacon_1         |      at picocli.CommandLine.access$1100(CommandLine.java:145) [picocli-4.4.0.jar:4.4.0]
beacon_1         |      at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332) [picocli-4.4.0.jar:4.4.0]
beacon_1         |      at picocli.CommandLine$RunLast.handle(CommandLine.java:2326) [picocli-4.4.0.jar:4.4.0]
beacon_1         |      at picocli.CommandLine$RunLast.handle(CommandLine.java:2291) [picocli-4.4.0.jar:4.4.0]
beacon_1         |      at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159) [picocli-4.4.0.jar:4.4.0]
beacon_1         |      at picocli.CommandLine.execute(CommandLine.java:2058) [picocli-4.4.0.jar:4.4.0]
beacon_1         |      at tech.pegasys.teku.cli.BeaconNodeCommand.parse(BeaconNodeCommand.java:231) [teku-21.4.0.jar:21.4.0]
beacon_1         |      at tech.pegasys.teku.Teku.main(Teku.java:32) [teku-21.4.0.jar:21.4.0]
beacon_1         | Caused by: org.rocksdb.RocksDBException: You have to open all column families. Column families not opened: 
beacon_1         |      at org.rocksdb.TransactionDB.open(Native Method) ~[rocksdbjni-6.11.4.jar:?]
beacon_1         |      at org.rocksdb.TransactionDB.open(TransactionDB.java:90) ~[rocksdbjni-6.11.4.jar:?]
beacon_1         |      at tech.pegasys.teku.storage.server.rocksdb.core.RocksDbInstanceFactory.create(RocksDbInstanceFactory.java:83) ~[teku-storage-21.4.0.jar:21.4.0]
beacon_1         |      ... 22 more
beacon_1         | Failed to open database at path: /opt/teku/data/beacon/archive
```

> after deleting the data it starts up correctly and syncs

**Comment by ajsutton** [comment] 2021-04-26 23:39
I've tested this locally and can't reproduce it going between those two versions.  The error message indicates that a RocksDB column had previously been used on the stored database but was no longer being specified.  Adding new columns is allowed, but removing them is not backwards compatible.

There was a new column added in 21.4.0 and another new column added in 21.4.1 but none were removed.  Both those changes were in the archive database which is what's failing to open so it seems likely that somehow a newer version of Teku opened the database which created the additional columns though the user doesn't believe a `develop` version was used on that server.  In any case the latest teku release includes all the new columns so should work with the database if it's still available.

I'm not sure there's much more we can do to investigate unless we can get a copy of the db and its still failing to open with 21.4.1.

**Comment by stefa2k** [comment] 2021-04-27 07:16
Unfortunately I can't provide a db, because it was a prater testnet setup I just deleted the files and carried on to test our software. I can say for sure that it were these versions, but I can't rule out that we originally already migrated multiple times from older versions to newer versions and then to `21.3.2` (never going back in time but making upgrades multiple times). What exact versions we used exactly I can't say, we usually use all the releases and update and test as soon as you guys release a new one.

**Comment by ajsutton** [comment] 2021-05-19 01:39
Going to close this one as we don't have any further information to go on.  Thanks for taking the time to report it though - we've finished the database changes now anyway but if this does occur again being able to get a copy of the database would definitely be very useful.

**Closed as completed by ajsutton** 2021-05-19 01:39 UTC
