### ISSUE TITLE
Teku crash during sync - nil pointer exception

### ISSUE THREAD

**Issue by protolambda** [Consensys-Incorporated/teku#2580] opened 2020-08-15 20:16 UTC
### Description

Exception crashes Teku during sync. Cannot make progress syncing due to crashes.

### Acceptance Criteria
* [Criteria 1]

### Steps to Reproduce (Bug)
1. Sync medalla testnet, at some point it keeps crashing, within a minute or two after restart, consistently.

**Expected behavior:** [What you expect to happen]

Fetch blocks without nil pointer exception

**Actual behavior:** [What actually happens]

```
2020-08-15 20:10:22.853 | ioEventLoopGroup-3-2 | DEBUG | tech.pegasys.teku.sync.FetchBlockTask | FetchBlockTask       | Failed to fetch block 0x3801596e9686059773e5d0bf465dc71c67b5f1304c5b13f3b459467daff1a050
java.util.concurrent.CompletionException: java.lang.NullPointerException: No response received when single response expected
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2137) ~[?:?]
        at tech.pegasys.teku.networking.eth2.rpc.core.ResponseStreamImpl.completeSuccessfully(ResponseStreamImpl.java:75) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-db84fe39]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.lambda$completeRequest$0(Eth2OutgoingRequestHandler.java:146) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-db84fe39]
        at java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753) [?:?]
        at java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731) [?:?]
        at java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2172) [?:?]
        at tech.pegasys.teku.infrastructure.async.SafeFuture.thenAccept(SafeFuture.java:351) [teku-infrastructure-async-0.12.4-SNAPSHOT.jar:0.12.4-dev-db84fe39]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.completeRequest(Eth2OutgoingRequestHandler.java:143) [teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-db84fe39]
        at tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.complete(Eth2OutgoingRequestHandler.java:117) [teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-db84fe39]
        at tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.userEventTriggered(RpcHandler.java:184) [teku-networking-p2p-0.12.4-SNAPSHOT.jar:0.12.4-dev-db84fe39]
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1428) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:346) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:332) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:913) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.libp2p.etc.util.netty.mux.MuxChannel.onRemoteDisconnected(MuxChannel.kt:58) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.etc.util.netty.mux.AbstractMuxHandler.onRemoteDisconnect(AbstractMuxHandler.kt:72) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.mux.MuxHandler.channelRead(MuxHandler.kt:37) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageCodec.channelRead(ByteToMessageCodec.java:103) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NullPointerException: No response received when single response expected
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:897) ~[guava-29.0-jre.jar:?]
        at tech.pegasys.teku.networking.eth2.rpc.core.ResponseStreamImpl.lambda$expectSingleResponse$1(ResponseStreamImpl.java:42) ~[teku-networking-eth2-0.12.4-SNAPSHOT.jar:0.12.4-dev-db84fe39]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
        ... 55 more
```

**Frequency:** [What percentage of the time does it occur?]

### Versions (Add all that apply)
* Software version: [`teku --version`]: `teku/v0.12.4-dev-db84fe39/linux-x86_64/oracle_openjdk-java-14`
* Java version: [`java -version`] (docker)
* OS Name & Version: [`cat /etc/*release`]: `Ubuntu 18.04.4 LTS`
* Kernel Version: [`uname -a`]
* Virtual Machine software & version: [`vmware -v`]
* Docker Version: [`docker version`]: `19.03.12`
* Cloud VM, type, size: [Amazon Web Services I3-large]: AWS ec2 medium

**Comment by rolfyone** [comment] 2020-08-16 21:18
thanks for logging, I'll see if i can reproduce this now.

There was another ticket raised that was similar, but the syncing seemed to resolve once they got different clients, so hopefully I get to see this one...

**Comment by ajsutton** [comment] 2020-08-25 00:10
When you say crash, do you mean the sync stalls or the JVM actually exits?  A `NullPointerException` shouldn't cause the JVM to exit.  In fact, that error is being reported at debug level because `FetchBlockTask` is handling it correctly - the block request will be retried and that shouldn't affect sync at all.

**Comment by protolambda** [comment] 2020-08-25 10:53
It's been a while, not sure what caused the exit. I also hit a few memory problems, some related to bad setup (MiB vs MB memory limit configuration, different limits of docker and java not matching), as well as relatively high memory usage for what is otherwise a small machine. If you can catch the reason for the nil pointer that would be great, but I think the crash shortly after might have been docker shutting it down. Will soon re-deploy my teku nodes with more memory, and do a fresh sync.

**Comment by ajsutton** [comment] 2020-08-25 21:12
Ok, we did catch the `NullPointerException` and handled it as expected - it would have been completely unseen at the default log level but is included at DEBUG level to explain why the block wasn't fetched on that try.

Will close this for now since there's been a lot of memory usage improvements since and we don't have the actual cause for the crash to investigate further.  Feel free to reopen if it happens again.

**Closed as completed by ajsutton** 2020-08-25 21:12 UTC
Labels: bug 🐞, P2
