### ISSUE TITLE
Update to latest LevelDB

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3587] opened 2021-02-12 00:27 UTC
### Description
The fuse source LevelDB JNI wrapper hasn't been updated for quite a while.  We should create our own fork and upgrade to the latest LevelDB version.

**Comment by rolfyone** [comment] 2021-10-05 20:31
It's been reported that the old library will be a problem for anyone on windows, due to the age of the leveldb dll, so we should take this into account when setting priority.

**Comment by benjaminion** [comment] 2023-11-07 17:38
Closing this venerable issue as a duplicate of #6138

**Closed as completed by benjaminion** 2023-11-07 17:38 UTC
