### ISSUE TITLE
WARN - AbstractRouter internal error on message control / No active outbound stream to write data control

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2620] opened 2020-08-19 11:26 UTC
Seeing this a _lot_. I assume that some queue is full.

Probably a warning worth keeping, but (a) tidied up so that it is less intrusive, and (b) less frequent. Keep the full message at DEBUG level.

Version: teku/v0.12.4-dev-6e36dccf/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13

```
11:20:35.871 WARN  - AbstractRouter internal error on message control {
  ihave {
    topicID: "/eth2/e7a75d5a/beacon_block/ssz_snappy"
    messageIDs: "0GzeW3jHbJWB_fOracJItpjOzmpK3-8bJ08Mmh2CdMQ="
  }
}
 from peer PeerHandler(peerId=16Uiu2HAmErANTrwmBwcBzWVTfK57WnyNS1LN3EFw4wEZ7FhfytuD, stream=P2PChannelOverNetty(nettyChannel=[id: 0x2a57c69a/2340/false, L:Mux[/192.168.1.203:9000-2a57c69a/2340/false] - R:Mux[/65.140.70.66:13924-2a57c69a/2340/false]], isInitiator=false))
io.libp2p.core.InternalErrorException: No active outbound stream to write data control {
  iwant {
    messageIDs: "0GzeW3jHbJWB_fOracJItpjOzmpK3-8bJ08Mmh2CdMQ="
  }
}
        at io.libp2p.etc.util.P2PServiceSemiDuplex$SDPeerHandler.writeAndFlush(P2PServiceSemiDuplex.kt:20) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.pubsub.AbstractRouter.send(AbstractRouter.kt:336) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.pubsub.AbstractRouter.flushPending(AbstractRouter.kt:105) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.pubsub.AbstractRouter.flushAllPending(AbstractRouter.kt:100) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.pubsub.gossip.GossipRouter.broadcastInbound(GossipRouter.kt:253) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.pubsub.AbstractRouter.newValidatedMessages(AbstractRouter.kt:255) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.pubsub.AbstractRouter.onInbound(AbstractRouter.kt:234) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService.streamInbound(P2PService.kt:171) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelRead$1.invoke(P2PService.kt:51) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelRead$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:231) [jvm-libp2p-minimal-0.5.5-RELEASE.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]

```

**Comment by Nashatyrev** [comment] 2020-08-28 10:36
Reproduced this with test: 
Libp2p pubsub by design manages 2 streams per peer: 1 inbound-only and 1 outbound-only. When remote peer initiates a pubsub stream (locally inbound), local pubsub immediately creates another stream (outbound). Though JVM libp2p gossip doesn't send any messages until both streams are initiated this is not obligatory. Another implementation may immediately send a data as soon as just outbound stream is created. On our side this results in the described situation: we are receiving `IHAVE` right after inbound stream open and immediately issuing `IWANT` while the outbound stream is not yet established.

**Comment by Nashatyrev** [comment] 2020-08-31 14:19
Reopening until next Libp2p release merged

**Comment by benjaminion** [comment] 2020-09-01 15:58
I've just had 18000 of these in the last 5 hours. That's a _lot_ of logs 😄  Would be nice to make it quieter.

**Comment by Nashatyrev** [comment] 2020-09-01 16:09
Will do Libp2p release with the fix shortly

**Closed as completed** 2020-09-01 18:06 UTC
Labels: bug 🐞
