### ISSUE TITLE
Teku stuck in sync mode

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#2157] opened 2020-06-16 07:43 UTC
### Description
Teku gets stuck in sync mode until the peer eventually disconnects:

```

{"timestamp":"2020-06-16T07:34:12,354","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146271, Head slot: 146270, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:34:24,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146272, Head slot: 146271, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:34:36,347","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146273, Head slot: 146271, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:34:48,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146274, Head slot: 146273, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:35:00,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146275, Head slot: 146274, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:35:12,351","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146276, Head slot: 146274, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:35:24,349","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146277, Head slot: 146276, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:35:36,347","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146278, Head slot: 146277, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:35:48,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146279, Head slot: 146277, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:36:00,349","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146280, Head slot: 146279, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:36:12,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146281, Head slot: 146280, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:36:24,347","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146282, Head slot: 146281, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:36:36,351","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146283, Head slot: 146282, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:36:48,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146284, Head slot: 146283, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:37:00,347","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146285, Head slot: 146283, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:37:12,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146286, Head slot: 146285, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:37:24,347","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146287, Head slot: 146285, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:37:36,347","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146288, Head slot: 146285, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:37:48,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Sync Event  *** Current slot: 146289, Head slot: 146285, Connected peers: 23","throwable":""}
{"timestamp":"2020-06-16T07:37:54,380","level":"ERROR","thread":"LibP2PNetwork-19","class":"SyncManager","message":"Error during sync to peer Eth2Peer{id=16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv, remoteStatus=Optional[PeerStatus{forkDigest=0xf6775d07, finalizedRoot=0xabfa25a62fd102f81bbac4595d7cbc262c3e50fa08710bfea6b78664c156d2c4, finalizedEpoch=4034, headRoot=0xe563ad20f3706a228a446a9d40753932edf7ca10af837807b0c26794a29460d4, headSlot=146280}]}","throwable":" java.util.concurrent.CompletionException: tech.pegasys.teku.networking.p2p.peer.PeerDisconnectedException\n\tat java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:743)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)\n\tat java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)\n\tat tech.pegasys.teku.util.async.SafeFuture.thenAccept(SafeFuture.java:299)\n\tat tech.pegasys.teku.networking.eth2.peers.Eth2Peer.sendRequest(Eth2Peer.java:224)\n\tat tech.pegasys.teku.networking.eth2.peers.Eth2Peer.requestStream(Eth2Peer.java:217)\n\tat tech.pegasys.teku.networking.eth2.peers.Eth2Peer.requestBlocksByRange(Eth2Peer.java:174)\n\tat tech.pegasys.teku.sync.PeerSync.lambda$executeSync$2(PeerSync.java:108)\n\tat java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)\n\tat java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)\n\tat tech.pegasys.teku.util.async.SafeFuture.thenCompose(SafeFuture.java:312)\n\tat tech.pegasys.teku.sync.PeerSync.executeSync(PeerSync.java:101)\n\tat tech.pegasys.teku.sync.PeerSync.lambda$executeSync$3(PeerSync.java:119)\n\tat java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.ResponseStreamImpl.completeSuccessfully(ResponseStreamImpl.java:74)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.lambda$completeRequest$0(Eth2OutgoingRequestHandler.java:141)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptNow(CompletableFuture.java:753)\n\tat java.base/java.util.concurrent.CompletableFuture.uniAcceptStage(CompletableFuture.java:731)\n\tat java.base/java.util.concurrent.CompletableFuture.thenAccept(CompletableFuture.java:2108)\n\tat tech.pegasys.teku.util.async.SafeFuture.thenAccept(SafeFuture.java:299)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.completeRequest(Eth2OutgoingRequestHandler.java:138)\n\tat tech.pegasys.teku.networking.eth2.rpc.core.Eth2OutgoingRequestHandler.processInput(Eth2OutgoingRequestHandler.java:109)\n\tat tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler$Controller.lambda$setRequestHandler$0(RpcHandler.java:202)\n\tat tech.pegasys.teku.util.async.SafeFuture.fromRunnable(SafeFuture.java:104)\n\tat tech.pegasys.teku.util.async.AsyncRunner.lambda$runAsync$0(AsyncRunner.java:24)\n\tat tech.pegasys.teku.util.async.SafeFuture.ofComposed(SafeFuture.java:84)\n\tat tech.pegasys.teku.util.async.DelayedExecutorAsyncRunner.lambda$runAsync$1(DelayedExecutorAsyncRunner.java:59)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\nCaused by: tech.pegasys.teku.networking.p2p.peer.PeerDisconnectedException\n\tat tech.pegasys.teku.networking.p2p.libp2p.rpc.RpcHandler.lambda$sendRequest$0(RpcHandler.java:72)\n\tat tech.pegasys.teku.util.async.SafeFuture.lambda$always$10(SafeFuture.java:198)\n\tat tech.pegasys.teku.util.async.SafeFuture.lambda$finish$12(SafeFuture.java:207)\n\tat java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:930)\n\tat java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:907)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)\n\tat tech.pegasys.teku.util.async.SafeFuture.lambda$propagateResult$2(SafeFuture.java:97)\n\tat java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)\n\tat java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)\n\tat java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)\n\tat java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)\n\tat io.libp2p.etc.types.NettyExtKt$toCompletableFuture$1.operationComplete(NettyExt.kt:15)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)\n\tat io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)\n\tat io.netty.util.concurrent.DefaultPromise.access$200(DefaultPromise.java:35)\n\tat io.netty.util.concurrent.DefaultPromise$1.run(DefaultPromise.java:501)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\t... 1 more\n"}
{"timestamp":"2020-06-16T07:38:04,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Slot Event  *** Slot: 146290, Block: 5b2614..578a, Epoch: 4571, Finalized checkpoint: 4034, Finalized root: abfa25..d2c4, Peers: 22","throwable":""}
{"timestamp":"2020-06-16T07:38:16,348","level":"INFO","thread":"TimeTickChannel-0","class":"teku-event-log","message":"Slot Event  *** Slot: 146291, Block:    ... empty, Epoch: 4571, Finalized checkpoint: 4034, Finalized root: abfa25..d2c4, Peers: 22","throwable":""}
```

**Comment by ajsutton** [comment] 2020-07-01 05:43
This happened again.  I switched to TRACE mode for a while and there was a ton of failures to receive metadata requests and discovery errors but the last relevant method I found was:

{"timestamp":"2020-07-01T05:35:10,969","level":"DEBUG","thread":"beaconchain-async-0","class":"PeerSync","message":"Request 200 blocks starting at 242041 from peer 16Uiu2HAmVKjTm3YePQgQLxm3fsfAUVgE58opRHZGDXRNLNsqvzBv","throwable":""}


We should have printed that the request was complete or failed after than but it never happened.  Looks like somehow the request is hanging forever and we're either not timing out or the timeout isn't cancelling the waiting future correctly.

**Comment by mbaxter** [comment] 2020-07-01 22:53
> This happened again.

This most recent event happened when syncing witti during a period of non-finalization using the build from this PR: https://github.com/PegaSysEng/teku/pull/2284

**Comment by mbaxter** [comment] 2020-07-07 22:00
I've reproduced this in 2 out of 3 runs on witti syncing from ~block 210,000.  The sync does continue pulling blocks, but fork-choice stops updating the head block so that it looks like sync has halted.  Both times I've reproduced this issue, the head has gotten stuck at block 225055 (block root: 0x4f295c745c8de6c4b37055a34b5d4c5680a59d6b836b50e072509a78d2994b2b).

**Comment by mbaxter** [comment] 2020-07-13 18:39
Fork choice is getting "stuck" at block 225055 because:
* While we're syncing, all `ProtoNode`'s have a [`weight`](https://github.com/PegaSysEng/teku/blob/d9fdf128e70b7cc4d5d0b556f1bea20f17b7bf22/protoarray/src/main/java/tech/pegasys/teku/protoarray/ProtoNode.java#L34) of 0.
    * `ProtoNode` weights are based on attestations, but we ignore attestations that are not from [the current or previous epoch](https://github.com/PegaSysEng/teku/blob/d9fdf128e70b7cc4d5d0b556f1bea20f17b7bf22/ethereum/core/src/main/java/tech/pegasys/teku/core/ForkChoiceUtil.java#L413-L416).  So, historical nodes don't get updated with any weights while we're syncing.
* Block 225053 (root: 0xd4e8f60d63b2f7a664aa7975568c64cba680298f4e768ea41d748d34619eb945) has 2 children:
    * Block 225054 (root: 0x3538af34cfa389d6efa8aa102a71437e16851bdd60a6754e723fc4c6936d8bd4)
        * This block has thousands of descendants
    * Block 225055 (root: 0x4f295c745c8de6c4b37055a34b5d4c5680a59d6b836b50e072509a78d2994b2b)
        * This block is a dead-end fork with no descendants
* We choose our fork-choice head based on weight (which is 0), and [tie-break based on hash](https://github.com/PegaSysEng/teku/blob/d9fdf128e70b7cc4d5d0b556f1bea20f17b7bf22/protoarray/src/main/java/tech/pegasys/teku/protoarray/ProtoArray.java#L321-L326).  So, block 225053 has its best child / best descendent set to block 225055, and all of its ancestors are updated to point to block 225055 as the best descendant.
* The head will be stuck here until we either start processing attestations again (sync up to a very recent slot) or justify a new block that is incompatible with the current head.

**Comment by mbaxter** [comment] 2020-07-14 21:46
Closing this ticket since it isn't really a "bug".  Added a follow-up ticket to look into improving `teku`'s output in this case to make it clearer what's happening: #2353

**Closed as completed by mbaxter** 2020-07-14 21:46 UTC
Labels: bug 🐞, P2
