### ISSUE TITLE
No attestations on Prater testnet

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#4056] opened 2021-06-03 11:37 UTC
### Description

Teku with initial state on Prater testnet does not attest. No indication in logs that it is even aware of its duties. Validator key is shown as loaded in logs.

### Versions (Add all that apply)
* Software version: `teku/v21.5.0/linux-x86_64/oracle_openjdk-java-15`

### Additional Information

This validator: https://prater.beaconcha.in/validator/0xa472cf65cd30b98234d9a1fcd6e50520f5c5d2e7d1b7e6beb1c7a0c064764d79b945e000b8a3d245cd0d87e1f3996e22#attestations

```
consensus_1         | 11:30:35.323 INFO  - Loaded 1 Validators: a472cf6
consensus_1         | 11:30:40.135 INFO  - Storage initialization complete
consensus_1         | 11:30:40.135 WARN  - Not loading specified initial state as chain data already exists.
consensus_1         | 11:30:43.394 INFO  - Completed regeneration of block 0x9a62f028ba6dd921c8e2daa78850e475c8ef3aa38d3414355f2e007834f8899d at slot 321344 by replaying 32 blocks. Took 3223ms
consensus_1         | 11:30:44.683 INFO  - Loading generated p2p private key from: generated-node-key
consensus_1         | 11:30:45.862 INFO  - PreGenesis Local ENR: enr:-KG4QKSmCFCRM_Gp8feqtSvgw4FcC4JgOIMAKonrUWof5fnyMBtZRmM22dc20KwAwJXaTrN1W6ki4OG4JYeNX0M8x1EihGV0aDKQ5L6TkwAAECD__________4JpZIJ2NIJpcISsGwACiXNlY3AyNTZrMaEDk-IzXmWBRPRJRmIN_tW26yiWsE5bzGdMfS1aJRKWbtCDdGNwgiMog3VkcIIjKA
consensus_1         | 11:30:45.868 INFO  - Using multipeer sync
consensus_1         | 11:30:46.061 INFO  - Logging initialized @18221ms to org.eclipse.jetty.util.log.Slf4jLog
consensus_1         | 11:30:46.279 INFO  - Starting Javalin ...
consensus_1         | 11:30:46.367 INFO  - jetty-9.4.31.v20200723; built: 2020-07-23T17:57:36.812Z; git: 450ba27947e13e66baa8cd1ce7e85a4461cacc1d; jvm 15.0.2+7-27
consensus_1         | 11:30:46.771 INFO  - Started ServerConnector@63cd0fa2{HTTP/1.1, (http/1.1)}{0.0.0.0:5051}
consensus_1         | 11:30:46.772 INFO  - Started @18974ms
consensus_1         | 11:30:46.772 INFO  - Listening on http://localhost:5051/
consensus_1         | 11:30:46.772 INFO  - Javalin started in 493ms \o/
consensus_1         | 11:30:46.799 INFO  - Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
consensus_1         | 11:30:47.098 INFO  - The latest finalized checkpoint at epoch 10041 fell outside of the weak subjectivity period after epoch 12930, which is prior to the current epoch 16176.
consensus_1         | 11:30:47.104 INFO  - The latest finalized checkpoint at epoch 10041 is outside of the weak subjectivity period.  Please supply a recent weak subjectivity checkpoint using --ws-checkpoint=<BLOCK_ROOT>:<EPOCH>.
consensus_1         | 11:30:47.502 INFO  - Successfully loaded deposits up to Eth1 block 4902531
consensus_1         | 11:30:48.004 INFO  - Completed regeneration of block 0x83b47617d0afa075e337996624d137c770068633901a3d89af56ea1909892380 at slot 321406 by replaying 59 blocks. Took 3768ms
consensus_1         | 11:30:48.019 INFO  - Starting libp2p network...
consensus_1         | 11:30:48.103 INFO  - Listening for connections on: /ip4/172.27.0.2/tcp/9000/p2p/16Uiu2HAmNcGLPtsf2VaJxS8PLDVGo9XooqxNkHxN4DSFTeWp9xj1
consensus_1         | 11:30:48.106 INFO  - Starting discovery server on UDP port 9000
consensus_1         | 11:30:48.169 INFO  - Skipping head block update to avoid potential rollback of the chain head.
consensus_1         | 11:30:48.174 INFO  - UDP discovery client started
consensus_1         | 11:30:48.282 INFO  - Local ENR: enr:-KG4QI306YP9Nnw7x28-3ARGhqDypRuJZhbtUZgdZEVz0p0sElu9g5yG14ayoMW5MAZiTXAnVLcOlCB7nEOpMFefTDsjhGV0aDKQed8EKAAAECD__________4JpZIJ2NIJpcISsGwACiXNlY3AyNTZrMaEDk-IzXmWBRPRJRmIN_tW26yiWsE5bzGdMfS1aJRKWbtCDdGNwgiMog3VkcIIjKA
consensus_1         | 11:30:49.964 INFO  - Sync Event  *** Current slot: 517654, Head slot: 321406, Connected peers: 1
consensus_1         | 11:31:07.580 INFO  - Completed regeneration of block 0x13d95922764c50399ea1d3fa26b56342e01a21601a05a9832fe32961a5565e67 at slot 321376 by replaying 29 blocks. Took 7281ms
consensus_1         | 11:31:10.808 INFO  - Sync Event  *** Current slot: 517655, Head slot: 321421, Connected peers: 1
consensus_1         | 11:31:15.097 INFO  - Sync Event  *** Current slot: 517656, Head slot: 321425, Connected peers: 1
consensus_1         | 11:31:25.592 INFO  - Sync Event  *** Current slot: 517657, Head slot: 321433, Connected peers: 2
consensus_1         | 11:31:37.762 INFO  - Sync Event  *** Current slot: 517658, Head slot: 321449, Connected peers: 10
consensus_1         | 11:31:49.472 INFO  - Sync Event  *** Current slot: 517659, Head slot: 321468, Connected peers: 10
consensus_1         | 11:32:03.511 INFO  - Sync Event  *** Current slot: 517660, Head slot: 321484, Connected peers: 20
consensus_1         | 11:32:13.070 INFO  - Sync Event  *** Current slot: 517661, Head slot: 321501, Connected peers: 20
consensus_1         | 11:32:24.987 INFO  - Sync Event  *** Current slot: 517662, Head slot: 321517, Connected peers: 20
consensus_1         | 11:32:37.729 INFO  - Sync Event  *** Current slot: 517663, Head slot: 321537, Connected peers: 20
consensus_1         | 11:32:37.735 INFO  - Epoch Event *** Epoch: 16177, Justified checkpoint: 10047, Finalized checkpoint: 10046, Finalized root: 65e546..25dc
consensus_1         | 11:32:48.819 INFO  - Sync Event  *** Current slot: 517664, Head slot: 321558, Connected peers: 20
consensus_1         | 11:33:01.127 INFO  - Sync Event  *** Current slot: 517665, Head slot: 321578, Connected peers: 20
consensus_1         | 11:33:13.048 INFO  - Skipping head block update as justified checkpoint was updated while loading checkpoint state. Was 10048 (0xa7c57a562ddd67f9d5f577254cfd6555f70e22df16a9b9d0b131b2ff543e0f10) but now 10049 (0x90b09bd4a285f79824b5987698764fbe47a960ca3d329c98cadcdb75b111544f)
consensus_1         | 11:33:13.049 INFO  - Sync Event  *** Current slot: 517666, Head slot: 321600, Connected peers: 20
consensus_1         | 11:33:25.180 INFO  - Sync Event  *** Current slot: 517667, Head slot: 321620, Connected peers: 22
consensus_1         | 11:33:36.898 INFO  - Sync Event  *** Current slot: 517668, Head slot: 321638, Connected peers: 28
consensus_1         | 11:33:49.189 INFO  - Sync Event  *** Current slot: 517669, Head slot: 321660, Connected peers: 27
consensus_1         | 11:34:04.190 INFO  - Sync Event  *** Current slot: 517670, Head slot: 321681, Connected peers: 27
consensus_1         | 11:34:13.070 INFO  - Sync Event  *** Current slot: 517671, Head slot: 321695, Connected peers: 27
```

**Comment by yorickdowne** [comment] 2021-06-03 11:42
After deleting chain DB and starting over, Teku logs that it attested, but actually did not. Watching for another epoch.

The epoch after that, Teku correctly attested.

What had been done was to give Teku an initial state and load a key that had not yet been activated. Curious as to how it got into a state where it didn't track finalized epoch correctly and did not attest, from there.

```
consensus_1         | 11:40:40.130 INFO  - Slot Event  *** Slot: 517703, Block: 206396..9e1c, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 2
consensus_1         | 11:40:52.138 INFO  - Slot Event  *** Slot: 517704, Block: bc65ce..9279, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 2
consensus_1         | 11:40:59.083 WARN  - Validator   *** Skipped aggregation for committee 16 at slot 517700 because there was nothing to aggregate
consensus_1         | 11:40:59.092 INFO  - Validator   *** Published attestation        Count: 1, Slot: 517700, Root: ccc254..2dee
consensus_1         | 11:41:00.013 INFO  - Updating number of persistent subnet subscriptions from 0 to 1
consensus_1         | 11:41:00.509 INFO  - Validator a472cf6 status is active_ongoing.
consensus_1         | 11:41:04.116 INFO  - Slot Event  *** Slot: 517705, Block:    ... empty, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 2
consensus_1         | 11:41:16.114 INFO  - Slot Event  *** Slot: 517706, Block: 5fc4f5..5ab9, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 2
consensus_1         | 11:41:28.122 INFO  - Slot Event  *** Slot: 517707, Block: 240e1a..dec9, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 2
consensus_1         | 11:41:40.123 INFO  - Slot Event  *** Slot: 517708, Block: f2ee4d..043b, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 2
consensus_1         | 11:41:52.122 INFO  - Slot Event  *** Slot: 517709, Block: 2a52d4..1532, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 2
consensus_1         | 11:42:04.112 INFO  - Slot Event  *** Slot: 517710, Block: bcd1f2..ce54, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 2
consensus_1         | 11:42:16.128 INFO  - Slot Event  *** Slot: 517711, Block: 0a6e64..3763, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 13
consensus_1         | 11:42:28.112 INFO  - Slot Event  *** Slot: 517712, Block: 36b6a0..9166, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 13
consensus_1         | 11:42:40.126 INFO  - Slot Event  *** Slot: 517713, Block: f41fd7..7c2f, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 24
consensus_1         | 11:42:52.123 INFO  - Slot Event  *** Slot: 517714, Block: 1a4c7a..9fd6, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 24
consensus_1         | 11:43:04.379 INFO  - Slot Event  *** Slot: 517715, Block: 0aa0b7..2aef, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 24
consensus_1         | 11:43:16.391 INFO  - Slot Event  *** Slot: 517716, Block: 21a193..a0f2, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 27
consensus_1         | 11:43:28.286 INFO  - Slot Event  *** Slot: 517717, Block: 52a390..7d72, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 27
consensus_1         | 11:43:40.113 INFO  - Slot Event  *** Slot: 517718, Block: 14be28..6ee5, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 28
consensus_1         | 11:43:52.395 INFO  - Slot Event  *** Slot: 517719, Block: 97687e..68db, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 28
consensus_1         | 11:44:04.268 INFO  - Slot Event  *** Slot: 517720, Block: 44c0e7..0683, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 28
consensus_1         | 11:44:16.395 INFO  - Slot Event  *** Slot: 517721, Block: a2f59a..fdbb, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 28
consensus_1         | 11:44:28.363 INFO  - Slot Event  *** Slot: 517722, Block: 22b6ae..e8f1, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 28
consensus_1         | 11:44:40.361 INFO  - Slot Event  *** Slot: 517723, Block: d687f0..62e1, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 33
consensus_1         | 11:44:52.270 INFO  - Slot Event  *** Slot: 517724, Block: 8c56a5..010d, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 33
consensus_1         | 11:45:04.220 INFO  - Slot Event  *** Slot: 517725, Block: eafc19..2c5a, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 33
consensus_1         | 11:45:16.107 INFO  - Slot Event  *** Slot: 517726, Block: 3f94b8..ab66, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 33
consensus_1         | 11:45:28.301 INFO  - Slot Event  *** Slot: 517727, Block: 7d1acd..1987, Epoch: 16178, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4, Peers: 32
consensus_1         | 11:45:36.022 INFO  - Epoch Event *** Epoch: 16179, Justified checkpoint: 16177, Finalized checkpoint: 16176, Finalized root: 890e88..bbd4
consensus_1         | 11:45:36.093 INFO  - Attestation performance: expected 0, produced 0, included 0 (0%), distance 0 / 0.00 / 0, correct target 0 (0%), correct head 0 (0%)
```

**Comment by ajsutton** [comment] 2021-06-03 12:33
I suspect on the first attempt it actually started from an existing database so didn't load the initial state and was still syncing:
```
consensus_1         | 11:30:40.135 WARN  - Not loading specified initial state as chain data already exists.
```

and it was still syncing at the end of the quoted logs:
```
consensus_1         | 11:34:13.070 INFO  - Sync Event  *** Current slot: 517671, Head slot: 321695, Connected peers: 27
```

Note the head slot is still a fair way behind so it clearly started from some time well before the latest finalized epoch.


> Teku logs that it attested, but actually did not. 

In this case it did publish the attestation, but because attestations can be included up to an epoch later, the performance metrics always lag so the "Attestation performance" report is actually related to two epochs prior when the beacon node wasn't aware of any validators it was responsible for running.

**Comment by yorickdowne** [comment] 2021-06-03 12:42
I had restarted it at that point, it had been up for two days and had started from a fresh DB, and did get initial state, but never started attesting. The logs before restart are gone.

I can try and reproduce this and keep the logs that time.

**Comment by ajsutton** [comment] 2021-06-08 21:58
Apologies for the delay in getting back to you on this one.  I'm not sure exactly what happened, but the logs are exactly what you should see for a node that's syncing.  The "Current slot" is based off of clock time so it's high but the finalized epoch only updates as blocks are imported and it's exactly in line with where the "Head slot" is up to.

We'd need the logs of the first run when the sync started to know why the initial state wasn't used.

**Comment by yorickdowne** [comment] 2021-06-09 21:39
Understood. This is likely a very specific set of circumstances. I’ll try to recreate.

**Comment by ajsutton** [comment] 2021-07-02 02:43
I'm going to close this one as can't reproduce for now just to keep things neat, but please do reopen it if you find more info.

**Closed as completed by ajsutton** 2021-07-02 02:43 UTC
