### ISSUE TITLE
--log-file-name-pattern default incorrect

### ISSUE THREAD

**Issue by ajsutton** [Consensys-Incorporated/teku#3364] opened 2020-12-04 20:20 UTC
### Description
The default log file location is under the data base dir, but the logFileNamePattern has a hard coded default instead of moving with --data-base-dir.  Logs should rotate to the same directory as the main log file.

**Comment by rolfyone** [comment] 2020-12-07 00:29
closing as a duplicate of #3360

**Closed as completed by rolfyone** 2020-12-07 00:29 UTC
