### ISSUE TITLE
We should validate blocksByRange responses

### ISSUE THREAD

**Issue by arash009** [Consensys-Incorporated/teku#1964] opened 2020-05-26 05:25 UTC
We should validate that BeaconBlocksByRange responses are contiguous.  Currently `PeerSync` is the only place where we request a range of blocks.  We'll disconnect the peer if we receive a block with an unknown parent.  But if we happen to have the parent anyway, we won't penalize a peer that sends non-contiguous blocks.

See: https://github.com/PegaSysEng/teku/blob/550fd08d1394f273c1c95aa1210cc2fdf92acf44/sync/src/main/java/tech/pegasys/artemis/sync/PeerSync.java#L178-L187

**Comment by ajsutton** [comment] 2020-08-04 10:37
Duplicate of #2388

**Closed as completed by ajsutton** 2020-08-04 10:37 UTC
Labels: TeamCentaur
