### ISSUE TITLE
No peer available gossip topic 

### ISSUE THREAD

**Issue by alepacheco** [Consensys-Incorporated/teku#6653] opened 2022-12-28 19:51 UTC
### Description
Attestations are not been included because no peers for the gossip topic are found 

### Steps to Reproduce (Bug)
Unsure 

**Expected behavior:** Published attestation 

**Actual behavior:** Missed attestation 

**Frequency:** A few times a day

![BEA94060-74B7-473C-AB10-73B2AF19BF55](https://user-images.githubusercontent.com/8210939/209865090-5cb19b42-1188-4cab-8c0e-db4be6e19efc.png)

**Comment by benjaminion** [comment] 2022-12-28 20:34
This is a duplicate of #6527, so I'll close this one so that we have all the conversation in one place.

**Closed as completed by benjaminion** 2022-12-28 20:34 UTC
