### ISSUE TITLE
add metric for currently scheduled sync committee duties

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#5706] opened 2022-06-06 01:30 UTC
```
# TYPE validator_scheduled_attestation_duties_current gauge
# TYPE validator_scheduled_block_duties_current gauge
```

We should add a gauge for sync committee duties so that it's possible to easily determine that we have sync committee duties via metrics.

**Comment by ajsutton** [comment] 2022-06-06 02:49
The catch here is that sync committees perform duties every slot. It probably makes more sense to add a gauge that reports the number of local validators in the current sync committee and one for the next sync committee (probably using a labelled gauge).

**Comment by ajsutton** [comment] 2022-12-02 00:14
Closing as a duplicate of #6270. This one was first but the other one has external people watching and more discussion. :)

**Closed as completed by ajsutton** 2022-12-02 00:14 UTC
