### ISSUE TITLE
`--Xnetwork-safe-slots-to-import-optimistically` can't be set to value lower than 128

### ISSUE THREAD

**Issue by marioevz** [Consensys-Incorporated/teku#5943] opened 2022-07-18 22:10 UTC
### Description

Test `syncing-with-chain-having-valid-transition-block` of branch https://github.com/marioevz/hive/tree/all-tests-plus-cl-clients starts two execution client nodes with two different PoW chains that reach the same Total Difficulty on the same height on different blocks, so the test expects the beacon node to only sync to the other node after the `SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` slots period has passed.

Test  is currently passing when the default `SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` value (128) is used. However when the value is reduced (see https://github.com/marioevz/hive/blob/4cc5298565e85f5babe96c34f16131a4ff8f8ddb/simulators/eth2/engine/scenarios.go#L54) to e.g. 16, the test waits 16 + 4 slots after the merge and then fails because the beacon node does not re-org.

The `SAFE_SLOTS_TO_IMPORT_OPTIMISTICALLY` value is also written to `config.yaml` file before start, see https://github.com/ethereum/hive/pull/605.

If a value higher than 128 is used, the test behaves as expected and passes, therefore this issue only affects the runtime of the hive optimistic sync test cases, it's not a breaking issue.

Also worth mentioning is that the chain has _not_ finalized before the 128 slots in this short-lived hive test net.

### Steps to Reproduce (Bug)
To reproduce, grab hive branch https://github.com/marioevz/hive/tree/all-tests-plus-cl-clients, modify https://github.com/marioevz/hive/blob/4cc5298565e85f5babe96c34f16131a4ff8f8ddb/simulators/eth2/engine/scenarios.go#L54 value to any value less than 128 (16 was used during testing) and run command:

```
hive --client go-ethereum,teku-bn,teku-vc --sim eth2/engine --sim.limit "/syncing-with-chain-having-valid-transition-block"
```

**Expected behavior:**

Teku should re-org to the alternate valid chain after 16 slots.

**Actual behavior:**

Teku still waits 128 slots to re-org.

**Frequency:**

Every time when the test case is run.

### Versions
* Software version: teku/v22.6.1+66-g02d6064/linux-x86_64/-eclipseadoptium-openjdk64bitservervm-java-17
* Java version: openjdk 17.0.3 2022-04-19
* OS Name & Version: Ubuntu 18.04.6 LTS
* Docker Version: Docker version 20.10.17, build 100c701

**Comment by ajsutton** [comment] 2022-07-19 00:26
From what I've looked at previously I *think* this was actually because we only kept retrying execution for 2 slots so it should be fixed by https://github.com/ConsenSys/teku/pull/5941

**Comment by ajsutton** [comment] 2022-07-19 01:19
Tried to run these tests but I'm getting failures from hive without much info:
```
./hive --client go-ethereum,teku-bn,teku-vc --sim eth2/engine --sim.limit "/syncing-with-chain-having-valid-transition-block" -loglevel 5
DBUG[07-19|11:16:19] docker daemon online                     version=20.10.13
INFO[07-19|11:16:19] building image                           image=hive/hiveproxy nocache=false pull=false
INFO[07-19|11:16:19] building 3 clients...
INFO[07-19|11:16:19] building image                           image=hive/clients/go-ethereum:latest dir=clients/go-ethereum nocache=false pull=false
INFO[07-19|11:16:20] building image                           image=hive/clients/teku-bn:latest dir=clients/teku-bn nocache=false pull=false
INFO[07-19|11:16:20] building image                           image=hive/clients/teku-vc:latest dir=clients/teku-vc nocache=false pull=false
INFO[07-19|11:16:20] building 1 simulators...
INFO[07-19|11:16:20] building image                           image=hive/simulators/eth2/engine:latest dir=simulators/eth2/engine nocache=false pull=false
EROR[07-19|11:16:34] image build failed                       image=hive/simulators/eth2/engine:latest err="The command '/bin/sh -c go build -o ./sim .' returned a non-zero code: 2"
The command '/bin/sh -c go build -o ./sim .' returned a non-zero code: 2
```

**Comment by marioevz** [comment] 2022-07-19 01:31
I pushed a new version of https://github.com/marioevz/hive/tree/all-tests-plus-cl-clients.

Could you try doing `docker build .` directly in the `./hive/simulators/eth2/engine` folder to see if this gives more information about the error?

**Comment by ajsutton** [comment] 2022-07-19 01:46
```
docker build .
[+] Building 46.7s (15/17)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                     0.0s
 => => transferring dockerfile: 657B                                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                                                                                                         0.0s
 => [internal] load metadata for docker.io/ethereum/client-go:v1.10.20                                                                                                                                                                   0.0s
 => [internal] load metadata for docker.io/library/golang:1-alpine                                                                                                                                                                       0.0s
 => [stage-2 1/4] FROM docker.io/library/alpine:latest                                                                                                                                                                                   0.0s
 => [geth 1/2] FROM docker.io/ethereum/client-go:v1.10.20                                                                                                                                                                                0.1s
 => [builder 1/5] FROM docker.io/library/golang:1-alpine                                                                                                                                                                                 0.1s
 => [internal] load build context                                                                                                                                                                                                        0.1s
 => => transferring context: 389.28kB                                                                                                                                                                                                    0.1s
 => CANCELED [geth 2/2] RUN  /usr/local/bin/geth makecache  1 /ethash &&  /usr/local/bin/geth makedag    1 /ethash                                                                                                                      46.6s
 => [builder 2/5] RUN apk --no-cache add gcc musl-dev linux-headers cmake make clang build-base clang-static clang-dev                                                                                                                  22.3s
 => [stage-2 2/4] ADD . /                                                                                                                                                                                                                0.0s
 => [builder 3/5] ADD . /source                                                                                                                                                                                                          0.0s
 => [builder 4/5] WORKDIR /source                                                                                                                                                                                                        0.0s
 => ERROR [builder 5/5] RUN go build -o ./sim .                                                                                                                                                                                         24.0s
------
 > [builder 5/5] RUN go build -o ./sim .:
#13 0.460 go: downloading github.com/ethereum/hive v0.0.0-20220707162108-7ef78bf4723f
#13 0.814 go: downloading github.com/ethereum/go-ethereum v1.10.20
#13 4.536 go: downloading github.com/golang-jwt/jwt/v4 v4.3.0
#13 4.536 go: downloading github.com/holiman/uint256 v1.2.0
#13 4.536 go: downloading github.com/protolambda/bls12-381-util v0.0.0-20210812140640-b03868185758
#13 4.537 go: downloading github.com/protolambda/eth2api v0.0.0-20220123235524-49a703ed9d94
#13 4.601 go: downloading github.com/protolambda/zrnt v0.26.1
#13 4.694 go: downloading github.com/protolambda/ztyp v0.2.2
#13 4.695 go: downloading github.com/marioevz/engine-proxy v0.0.0-20220617181151-e8661eb39eea
#13 4.741 go: downloading github.com/golang/snappy v0.0.4
#13 4.745 go: downloading github.com/olekukonko/tablewriter v0.0.5
#13 4.753 go: downloading github.com/prometheus/tsdb v0.10.0
#13 4.754 go: downloading github.com/VictoriaMetrics/fastcache v1.6.0
#13 4.758 go: downloading github.com/hashicorp/golang-lru v0.5.5-0.20210104140557-80c98217689d
#13 4.789 go: downloading golang.org/x/crypto v0.0.0-20211202192323-5770296d904e
#13 4.794 go: downloading github.com/go-stack/stack v1.8.1
#13 4.854 go: downloading github.com/deckarep/golang-set v1.8.0
#13 4.858 go: downloading github.com/gorilla/websocket v1.4.2
#13 5.035 go: downloading github.com/edsrzf/mmap-go v1.0.0
#13 5.035 go: downloading golang.org/x/sys v0.0.0-20220520151302-bc2c85ada10a
#13 5.089 go: downloading github.com/google/uuid v1.3.0
#13 5.145 go: downloading github.com/herumi/bls-eth-go-binary v0.0.0-20210902234237-7763804ee078
#13 5.222 go: downloading github.com/pkg/errors v0.9.1
#13 5.338 go: downloading github.com/protolambda/go-keystorev4 v0.0.0-20210914214957-cf12d9c28a52
#13 5.394 go: downloading github.com/tyler-smith/go-bip39 v1.1.0
#13 5.400 go: downloading github.com/wealdtech/go-eth2-util v1.6.5
#13 5.586 go: downloading gopkg.in/yaml.v2 v2.4.0
#13 5.593 go: downloading github.com/kilic/bls12-381 v0.1.0
#13 5.606 go: downloading github.com/julienschmidt/httprouter v1.3.0
#13 5.637 go: downloading gopkg.in/yaml.v3 v3.0.1
#13 5.673 go: downloading github.com/syndtr/goleveldb v1.0.1-0.20220614013038-64ee5596c38a
#13 5.758 go: downloading github.com/shirou/gopsutil v3.21.8+incompatible
#13 5.762 go: downloading github.com/sirupsen/logrus v1.8.1
#13 5.762 go: downloading github.com/holiman/bloomfilter/v2 v2.0.3
#13 5.763 go: downloading github.com/mattn/go-runewidth v0.0.13
#13 5.767 go: downloading github.com/cespare/xxhash/v2 v2.1.2
#13 5.820 go: downloading golang.org/x/text v0.3.7
#13 5.821 go: downloading github.com/wealdtech/go-bytesutil v1.1.1
#13 5.834 go: downloading github.com/wealdtech/go-eth2-types/v2 v2.5.6
#13 5.841 go: downloading github.com/minio/sha256-simd v1.0.0
#13 5.889 go: downloading github.com/rivo/uniseg v0.2.0
#13 5.908 go: downloading github.com/tklauser/go-sysconf v0.3.9
#13 6.031 go: downloading github.com/ferranbt/fastssz v0.0.0-20210905181407-59cf6761a7d5
#13 6.133 go: downloading github.com/klauspost/cpuid/v2 v2.0.9
#13 6.146 go: downloading github.com/tklauser/numcpus v0.3.0
#13 6.375 go: downloading github.com/mitchellh/mapstructure v1.4.2
#13 18.29 # github.com/herumi/bls-eth-go-binary/bls
#13 18.29 /usr/lib/gcc/aarch64-alpine-linux-musl/11.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: $WORK/b215/_x002.o: in function `_cgo_7750ccf52c70_Cfunc_blsSetGeneratorOfPublicKey':
#13 18.29 /tmp/go-build/cgo-gcc-prolog:834: undefined reference to `blsSetGeneratorOfPublicKey'
#13 18.29 collect2: error: ld returned 1 exit status
------
executor failed running [/bin/sh -c go build -o ./sim .]: exit code: 2
```

**Comment by ajsutton** [comment] 2022-07-19 08:29
Got hive working and confirmed this test is passing with the latest teku thanks to the execution retry improvements.

**Closed as completed by ajsutton** 2022-07-19 08:29 UTC
