### ISSUE TITLE
`shouldPassMergeTransitionUsingWebsocketsEngine` breaking very often

### ISSUE THREAD

**Issue by rolfyone** [Consensys-Incorporated/teku#6563] opened 2022-12-06 21:59 UTC
The shouldPassMergeTransitionUsingWebsocketsEngine AT is breaking quite often currently, we need to have a look and see if there's an actual problem, or if its related to using `swift` now.

**Comment by ajsutton** [comment] 2022-12-08 00:25
This is caused by a web3j bug: https://github.com/web3j/web3j/pull/1826
Sadly trying to work around it on the Teku side would make ATs significantly slower as we'd have to synchronously send each deposit transaction.

**Comment by ajsutton** [comment] 2022-12-22 00:51
Finishing this off will require getting web3j/web3j#1826 merged and into a new web3j release then pulling that into Teku.

**Comment by benjaminion** [comment] 2023-03-14 08:04
Web3j PR now merged. Waiting for release.

**Closed as completed** 2023-04-17 09:00 UTC
Labels: blocked by another PR/issue 💔
