### ISSUE TITLE
Feature: Support UTF-8 in graffiti, for the 🐼!

### ISSUE THREAD

**Issue by yorickdowne** [Consensys-Incorporated/teku#5897] opened 2022-07-06 11:19 UTC
### Description

When providing `🐼eth-docker🐼` as Graffiti, Teku throws this error message: `Invalid value for option '--validators-graffiti': '????eth-docker????' converts to 34 bytes. Input must be 32 bytes or less.`

Panda graffiti is clearly a necessary feature for The Merge.

**Comment by benjaminion** [comment] 2022-07-06 11:43
Looks like a duplicate of #5731.

This should be fixed by #5858 in the next release. It just missed the last release, unfortunately. It ought to work in the `:develop` image, however.

Closing for now, but please reopen if it continues to be a problem once v22.7.0 is out.

**Closed as completed by benjaminion** 2022-07-06 11:43 UTC
