### ISSUE TITLE
WARN: InternalErrorException: [peerHandler] not initialized yet

### ISSUE THREAD

**Issue by benjaminion** [Consensys-Incorporated/teku#2532] opened 2020-08-07 11:56 UTC
```
2020-08-07 06:42:34.364+00:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | AbstractRouter internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
        at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:82) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:61) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:231) [jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
2020-08-07 06:42:35.401+00:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | AbstractRouter internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
        at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:82) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:61) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:231) [jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
2020-08-07 06:42:35.401+00:00 | P2PService-event-thread-0 | WARN  | AbstractRouter | AbstractRouter internal error on message null from peer null
io.libp2p.core.InternalErrorException: [peerHandler] not initialized yet
        at io.libp2p.etc.util.P2PService$StreamHandler.getPeerHandler(P2PService.kt:82) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PServiceSemiDuplex.streamActive(P2PServiceSemiDuplex.kt:55) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:61) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$StreamHandler$channelActive$1.invoke(P2PService.kt:36) ~[jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at io.libp2p.etc.util.P2PService$runOnEventThread$1.run(P2PService.kt:231) [jvm-libp2p-minimal-0.5.4-RELEASE.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:830) [?:?]
2020-08-07 06:42:36.027+00:00 | TimeTickChannel-0 | INFO  | teku-event-log | ^[[37mSlot Event  *** Slot: 19712, Block: 8bab1f..e5e9, Epoch: 616, Finalized checkpoint: 614, Finalized root: a05251..eb90, Peers: 79^[[0m
```

teku/v0.12.3-dev-79ef540b/linux-x86_64/-privatebuild-openjdk64bitservervm-java-13

**Comment by ajsutton** [comment] 2020-08-10 02:55
Duplicate of #2359.  Just need to pull in a new libp2p release.

**Closed as completed** 2020-08-11 19:36 UTC
Labels: bug 🐞, P4
