### ISSUE TITLE
Teku node seems to sync at the same speed that the chain is progressing

### ISSUE THREAD

**Issue by lufa23** [Consensys-Incorporated/teku#3000] opened 2020-10-16 13:11 UTC
I have started a Teku node with `./teku --network=medalla --metrics-enabled --rest-api-enabled --rest-api-docs-enabled --metrics-categories=BEACON,PROCESS,LIBP2P,JVM,NETWORK,PROCESS`

I notice also that the node is syncing quite slow.
From what it appears from the log, it gets new head slots at the same rate that the current slot is rising.
If this is correct, the node will never be able to sync.
How can i let it sync faster?
<img width="1636" alt="Screenshot 2020-10-16 at 11 50 34" src="https://user-images.githubusercontent.com/67415638/96262066-905c3980-0fc1-11eb-8c13-eb4c87df9a78.png">

**Comment by ajsutton** [comment] 2020-10-18 22:44
This is definitely syncing a lot slower than it should.  Can you look at the top of the log file just after startup and check that it has the line:
```
BLS: loaded BLST library
```

BLST is the native version of the BLS library and is significantly faster than the pure-java version.   Sometimes it fails to load if the `/tmp/` directory isn't writable or is mounted with `noexec` set.

**Comment by ajsutton** [comment] 2020-10-18 22:45
Getting the full content of the Teku log file would be very useful it will be in `~/.local/share/teku/logs/`

**Comment by ajsutton** [comment] 2020-10-19 05:06
I was able to reproduce this locally and it appears to be some configuration issue with RocksDB causing it to be unable to keep up with the write load during sync.  RocksDB winds up using huge amounts of memory and when memory is exhausted has to delay writes while it completes its background processing.  

We'll need to do more in depth investigation to understand the cause of this, but for now I've reverted the default database version Teku creates to the previous v5 which doesn't exhibit this issue.  Unfortunately you will need to delete the database and start the sync again to get it to create the v5 database format.  You can confirm the v5 format was used with `cat ~/.local/share/teku/beacon/db.version` which should report `5` and not `6`.

**Comment by lufa23** [comment] 2020-10-19 09:06
this is the full content of the log:

[teku_2020-10-16.log](https://github.com/PegaSysEng/teku/files/5400492/teku_2020-10-16.log)

And no `BLS: loaded BLST library` appears in the log after launching it

Also, I deleted the database with `rm -r ~/.local/share/teku/beacon ` ,  made a `git pull`, and confirming the format through `cat ~/.local/share/teku/beacon/db.version` but i get a `6` in the logs, instead of a 5.  And the node is still syncing very slow

**Comment by mbaxter** [comment] 2020-10-19 17:58
Hey @lufa23 - are those logs from after you pulled the latest?   From those logs, it appears you're still running a version of teku prior to our change to default the database to version 5.  If you pull the latest and reset your db again, it should run with version 5.  

When teku starts up it prints a version line like: `Teku version: teku/v0.12.11-dev-97691bc1/linux-x86_64/oracle-java-15` which has the commit hash in it.  You can check that the commit hash matches the latest here: https://github.com/PegaSysEng/teku/commits/master.

**Comment by ajsutton** [comment] 2020-10-28 03:17
Going to close this as we haven't heard anything further back.  If this is still an issue could you please check you have the latest version which should create a version 5 database.  Feel free to reopen if it's still slow with a v5 database.

**Closed as completed by ajsutton** 2020-10-28 03:17 UTC
